### ISSUE TITLE
Refine assisted setup

### ISSUE THREAD

**Issue by wwood** [wurmlab/sequenceserver#135]
```
bash-3.2$ sequenceserver 

Could not locate BLAST+ binaries.

SequenceServer can use NCBI BLAST+ that you may have on your system already, or
download the correct package for itself. Please enter the path to NCBI BLAST+
or press Enter to download.

Press Ctrl+C to quit.

>> /Users/ben/Downloads/ncbi-blast-2.2.30+/bin


Database dir not set.

SequenceServer needs to know where your FASTA files or BLAST+ databases are.
Please enter the path to the relevant directory (default: current directory).

Press Ctrl+C to quit.

>>
```

This was a little confusing at first because nowhere does it say that setting the blast bin directory was successful, at first glance it is just asking the same question again.

**Comment by vivekiitkgp** [comment]
@wwood Agreed. I had a fix for that in a commit somewhere but wasn't merged due to major ongoing changes by Priyam. Thanks!

**Comment by wwood** [comment]
Along the same lines, be good to advise the user that sequenceserver is attempting to start, to make the error like below less confusing. This is a bit of a rare problem since I'm messing around with the config files separately while installing, but still, presumably is easy to fix with an extra print statement.
```
Database dir not set.

SequenceServer needs to know where your FASTA files or BLAST+ databases are.
Please enter the path to the relevant directory (default: current directory).

Press Ctrl+C to quit.

>> /home/ben/git/sequenceserver/db/
[2015-02-20 21:45:23] WARN  Will listen on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--host option).
** Oops! There was an error.
   Is SequenceServer already accessible at http://0.0.0.0:4567?
   Try running SequenceServer on another port, like so:

       sequenceserver -p 4570.
```

**Comment by yeban** [comment]
There's relevant input in #137. Should say "Looking for BLAST+ databases" before saying "BLAST+ databases couldn't be found".

**Comment by vivekiitkgp** [comment]
@yeban What does this need to be closed?
