### ISSUE TITLE
Auto-complete on osx when specifying the DB adds extra spaces

### ISSUE THREAD

**Issue by wwood** [wurmlab/sequenceserver#136]
```
Database dir not set.

SequenceServer needs to know where your FASTA files or BLAST+ databases are.
Please enter the path to the relevant directory (default: current directory).

Press Ctrl+C to quit.

>>/Users/ben/Downlo
```
then press tab becomes
```
/Users/ben/Downloads 
```
Note the extra space after downloads, even though I intended to specify a subfolder of Downloads.

This is on OSX  10.9.5, Ubuntu did not have this problem

**Comment by yeban** [comment]
Could you try this one @wwood? We use `readline` for autocompletion. The code for this is in `bin/sequenceserver`.

**Comment by wwood** [comment]
Hmm, I'm pretty busy for the next 4 weeks or so, not sure I will have the time. I will try though.

**Comment by yeban** [comment]
Ok. It's just that I can't reproduce this issue or I would have taken care of it.

**Comment by wwood** [comment]
Sure. This isn't the biggest problem though I'd say.

On 24 February 2015 at 13:44, Anurag Priyam <notifications@github.com>
wrote:

> Ok. It's just that I can't reproduce this issue or I would have taken care
> of it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yannickwurm/sequenceserver/issues/136#issuecomment-75694580>
> .
>



-- 
--
Ben Woodcroft
http://ecogenomic.org/users/ben-woodcroft <http://www.ecogenomic.org/>

**Comment by yannickwurm** [comment]
@wwood is this still an issue?

**Comment by wwood** [comment]
Yes, seems so I'm afraid. I just updated all my gems (including seqserv to 1.0.6), and got the same issue. Is this not reproducible by others?

I can also just reproduce with readline itself outside of seqserv using system ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

Clearly not our fault, seems an issue either with ruby itself or OSX packaging it. What to do? Not really our fault.. I suggest we do nothing.

**Comment by yannickwurm** [comment]
Agreed - can you add this as an FAQ?
