### ISSUE TITLE
Should always log location of config file to stdout

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/sequenceserver#142]
Startup looks like this: 

```
Yannick@n56-164 ~/g/p/sequenceserver> sequenceserver                                                                                                                     gh-pages!?
[2015-02-24 16:49:37] WARN  Will listen on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--host option).
** SequenceServer is ready.
   Go to http://0.0.0.0:4567 in your browser and start BLASTing!
   Press CTRL+C to quit.
```

It should additionally always log the full path of config file to stdout.

**Comment by yeban** [comment]
You can launch sequenceserver with `-D` flag to see all the logs. Without `-D` flag it only shows warnings and errors.

**Comment by yeban** [comment]
SequenceServer can run with or without a config file. SequenceServer always looks for the given (`-c`) or the default config file (`~/.sequenceserver.conf`) and reads it _if available_. If not, and
1. if sufficient CLI parameters are passed (`-d`, & `-b` if BLAST+ executables are not in `PATH`) it will start without any issue.
2. if one of `-b` or `-d` is is not passed, it will drop to interactive mode and write the input to config file so it doesn't go to interactive mode next time.

Accordingly, `-D` shows if SequenceServer read the configuration file, or it did not find one. I don't think logging config file should be made a special case.

**Comment by yeban** [comment]
As explained before, config file isn't special. SequenceServer can run with or without one. And with assisted setup many users can run SequenceServer without even knowing of the existence of a config file.
