### ISSUE TITLE
User Experience Points

### ISSUE THREAD

**Issue by IsmailM** [wurmlab/sequenceserver#157]
First time playing about with the new SS UI, and so here are a few points that stood out to me that could be improved:

* Some more white space (maybe 25px more) between the graphical overview figure 'View More' button and the HSP tabular overview - I think that it should make the button more easier to see...
* Add a 'Back to Top' button; Either a floating button or simply add to the bottom of the affixed side menu...
* Make the graphical overview responsive - Otherwise, it breaks the layout slightly when you slowly decrease the browser width. This [Stackoverflow Q](http://stackoverflow.com/questions/9400615/whats-the-best-way-to-make-a-d3-js-visualisation-layout-responsive#answer-9539361) shows a quick fix.
* Centre the 'BLAST' button on smaller screens - currently looks really weird on a screen sizes smaller than 992px (i.e. bootstrap's `@screen-sm-min`)... 

Any thoughts???

**Comment by vivekiitkgp** [comment]
Hey @IsmailM. Thanks for the input. Points 1, 4 are already on our list. It'd be great if you could go ahead and try fixing the rest two.

Let us know if you are working on them.

**Comment by yeban** [comment]
Thanks @IsmailM. We will take care of these.

How would a 'Back to Top' button be helpful?

**Comment by IsmailM** [comment]
Hey Priyam, Sure that's cool...

I did start on the responsive SVGs last night on the train home, so do have a look [here](https://github.com/IsmailM/sequenceserver/tree/responsive_SVGs)... As such the SVGs are now responsive... But it's not yet finished, I still have to add the `on resize` function  to the functions that run when clicking on the 'view more' / 'view less' buttons. Let me know if you'll take care of this, or if you want me to finish this...

With regards to the Back to Top button...

Some of the results will be absolutely  massive (especially when blasting well characterised proteins (e.g. insulin) against large dbs).... Since at times you may want to alter the parameters or rerun BLAST+ against a different query, you have to navigate back to the top of the page, which can be a total pain:

* The large page means it takes absolutely ages to scroll manually
* And most users using a mac with a touchpad or the magic mouse rarely use the scroll bar...
* And iPads and those Windows 8 touch devices do not have a scrollbar, so you have to manually scroll to the top... (Also the window 8 versions of browsers (chrome & IE11) do not have scroll bars)... 

A number of sites (despite having a much shorter height than some of our results) have gone with a floating button that is always present at all screen size... 

Moreover, beside this 'Back to Top', I think that it may be useful to have internal links through the document (i.e. to: BLAST, Graphical Overview, HSP Overview, Results,  BLAST Run Details etc.)...

**Comment by vivekiitkgp** [comment]
@IsmailM While I do get the point of having a `Back to Top` button, having many internal links as you suggested towards the end seems an overkill to me. It will take us more closer to the NCBI like style (riddled with links all over), something that we have tried to avoid.

May be we can strategically place a few.

**Comment by IsmailM** [comment]
Yep I agree...

Thinking about it, it's easy to navigate around the file if you're close to the top of the file (with the hsp overview, and the query number links in the sidebar) so I think that just a 'back to top' button would suffice.

**Comment by yeban** [comment]
Which won't be required either if we split the results to a new page. Right?

**Comment by IsmailM** [comment]
Yes, I don't think it would be necessary if the results are on a new page...


NB. I really like the fact the results are on the same page as the search form...

**Comment by yeban** [comment]
@IsmailM One reason I would like results on a separate page is because I want the ability to return to old results and opening results in separate page would greatly facilitate that. I'm of a mind to implement it soon (in release 1.1 maybe). Let me know if you would like to try.

**Comment by yeban** [comment]
I believe all of this has been addressed in the latest master.
