### ISSUE TITLE
Tabular summary of results per query should include hit length column.

### ISSUE THREAD

**Issue by yeban** [wurmlab/sequenceserver#169]
We provide hit length in hit details just before alignment. This makes it difficult to get an _overview_ of the length distribution of the most significant hits. An overview of the length of hits is one of the many uses of BLAST search, in manual curation for example.

Including a length column in the tabular summary of results per query, and perhaps making it sortable, is the simplest and next best option available to adding a length distribution graph/visualisation.

**Comment by vivekiitkgp** [comment]
I'm not sure if hit length distribution of hits is a significant parameter to a biologist. Instead, Query coverage (`qcov`) and Identity are more insightful (and are also done by NCBI). We could include the former.

@yannickwurm

**Comment by yeban** [comment]
Length of hits is very important to me as a bio curator. Could include other relevant columns as well.
