### ISSUE TITLE
Debug message

### ISSUE THREAD

**Issue by vivekiitkgp** [wurmlab/sequenceserver#175]
When PATH is not set, and no blast binary location is provided, a debug message says:
`DEBUG Will use NCBI BLAST+ at: $PATH`

Perhaps something like, `Searching PATH...` would be more helpful (for debug purposes) and technically correct.

**Comment by yeban** [comment]
SequenceServer doesn't "search" PATH. If bin is not set, SequenceServer assumes binaries to be available in PATH. So I don't see why the debug message is technically incorrect.

**Comment by vivekiitkgp** [comment]
I don't think there is any harm is stating that assumption explicitly. As in, `Will use` is a pretty strong indication that we have found BLAST binaries.

````
DEBUG Will use NCBI BLAST+ at : $PATH
...
Could not locate BLAST+ binaries
...
````

Just a matter of interpretation. I am not really pushing on this one.
