### ISSUE TITLE
Sidebar Bug

### ISSUE THREAD

**Issue by IsmailM** [wurmlab/sequenceserver#176]
If you open SS in a browser with a width smaller than 992px (i.e. when the sidebar is hidden), the sidebar width is set as 0px and the top offset is set as 0px (set by some jQuery [here](https://github.com/yannickwurm/sequenceserver/blob/master/public/js/sequenceserver.js#L771)).

As a result, if you then increase the browser width from a width smaller than 992px, the sidebar looks really weird and does not work properly...

**Comment by yeban** [comment]
Correct.

**Comment by yannickwurm** [comment]
What is the easy solution to this?

**Comment by yeban** [comment]
This was fixed sometime back.
