### ISSUE TITLE
Error message if BLAST process was terminated prematurely.

### ISSUE THREAD

**Issue by yeban** [wurmlab/sequenceserver#178]
If for some reason BLAST process launched by SequenceServer terminates pre-maturely we end up with  an empty output file which SequenceServer then tries to parse and throws the error: 

```
NoMethodError - undefined method `root' for nil:NilClass:
```

This error is then surfaced to the user as - Ooop! Looks like you found a bug in SequenceServer ... please report ... here's the stacktrace ...

The bug here is that this error need be caught by SequenceServer and an informative message shown to the user.

See - https://groups.google.com/forum/#!topic/sequenceserver/MQhn9t6wbuY

**Comment by yannickwurm** [comment]
Is disk is full an error that is caught? (e.g. this would make it impossible to write to tmpfile)?

**Comment by yeban** [comment]
Input error, disk full, no permission to create job dir, broken binaries - all are caught. As a result, we should never end up attempting to parse an empty XML file (which is what caused this issue).
