### ISSUE TITLE
Uninformative error message for unparseable FASTA deflines

### ISSUE THREAD

**Issue by Blahah** [wurmlab/sequenceserver#187]
BioRuby and pretty much every other FASTA parser in the world parses FASTA deflines like this:

```
>seqid|other stuff
```

However, they make an exception for certain NCBI-derived headers which look like this:

```
>dbname|seqid| other stuff
e.g...
>gb|Z49865.1 S.epidermidis pepA, pepB, pepC, pepI, pepP and pepT genes
```

In 2003 the NCBI claimed that this was the standard format for FASTA headers, although nobody else in the world considers it a standard. So occasionally someone produces a FASTA file where the deflines follow the NCBI format, but can't be parsed by most FASTA defline parsers. For example, the yeast genome reference deflines look like this:

```
>ref|NC_001133| [org=Saccharomyces cerevisiae] [strain=S288C] [moltype=genomic] [chromosome=I]
```

FASTA parsers interpret this as a sequence with `entry_id = 'ref'`, while the people who created the file obviously intended it to be interpreted as `entry_id = ref|NC_001133`. So when a file full of such sequences is parsed, all the sequences have the same ID. If you load such a file into SequenceServer you get this crash:

```
Something went wonky

Looks like you have encountered a bug in SequenceServer. Please could you
report this incident to our Google Group -
https://groups.google.com/forum/?fromgroups#!forum/sequenceserver

Error:
undefined method `downcase!' for nil:NilClass
/Users/rds45/.rvm/gems/ruby-2.1.2/gems/sequenceserver-1.0.2/lib/sequenceserver/database.rb:25:in `initialize'
/Users/rds45/.rvm/gems/ruby-2.1.2/gems/sequenceserver-1.0.2/lib/sequenceserver/database.rb:109:in `new'
/Users/rds45/.rvm/gems/ruby-2.1.2/gems/sequenceserver-1.0.2/lib/sequenceserver/database.rb:109:in `block (2 levels) in scan_databases_dir'
/Users/rds45/.rvm/gems/ruby-2.1.2/gems/sequenceserver-1.0.2/lib/sequenceserver/database.rb:106:in `each_line'
/Users/rds45/.rvm/gems/ruby-2.1.2/gems/sequenceserver-1.0.2/lib/sequenceserver/database.rb:106:in `block in scan_databases_dir'
/Users/rds45/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/open3.rb:199:in `popen_run'
/Users/rds45/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/open3.rb:93:in `popen3'
/Users/rds45/.rvm/gems/ruby-2.1.2/gems/sequenceserver-1.0.2/lib/sequenceserver/database.rb:102:in `scan_databases_dir'
/Users/rds45/.rvm/gems/ruby-2.1.2/gems/sequenceserver-1.0.2/lib/sequenceserver.rb:130:in `init_database'
/Users/rds45/.rvm/gems/ruby-2.1.2/gems/sequenceserver-1.0.2/lib/sequenceserver.rb:40:in `init'
/Users/rds45/.rvm/gems/ruby-2.1.2/gems/sequenceserver-1.0.2/bin/sequenceserver:131:in `block (2 levels) in <top (required)>'
/Users/rds45/.rvm/gems/ruby-2.1.2/gems/slop-3.6.0/lib/slop.rb:260:in `call'
/Users/rds45/.rvm/gems/ruby-2.1.2/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/Users/rds45/.rvm/gems/ruby-2.1.2/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/Users/rds45/.rvm/gems/ruby-2.1.2/gems/sequenceserver-1.0.2/bin/sequenceserver:12:in `<top (required)>'
/Users/rds45/.rvm/gems/ruby-2.1.2/bin/sequenceserver:23:in `load'
/Users/rds45/.rvm/gems/ruby-2.1.2/bin/sequenceserver:23:in `<main>'
/Users/rds45/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/rds45/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

This can be fixed by just renaming the FASTA entries...

```
$ sed 's/ref\|/ref_/g' broken.fa > fixed.fa
```

I would suggest that the appropriate way to handle this situation is to raise an informative error, telling the user what is likely to be wrong and how they can fix it. An alternative is to attempt to rescue the situation when first adding the database, and ask the user whether they would like to have SequenceServer automatically rename all the entries.

### Note: known sources of FASTA that cause this problem:

- [Yeast Genome Database](http://downloads.yeastgenome.org/sequence/S288C_reference/genome_releases/)
- Certain recent versions of Trinity (the devs have [agreed to fix it](https://github.com/trinityrnaseq/trinityrnaseq/issues/21))

**Comment by yeban** [comment]
Thanks, that's very detailed. But I don't think that's the reason at all
for this error. This error is most often raised because the BLAST databases
were created by an older version of BLAST, and BLAST 2.2.30 is failing to
parse that. Another reason for this error that I've seen twice already is
incorrect file permission on the database files.

In your case, eventually recreating the BLAST database is probably what
solved the problem and not renaming sequence ids in FASTA. Because, the
following FASTA doesn't raise any error for me:

>ref|NC_001133| [org=Saccharomyces cerevisiae] [strain=S288C]
[moltype=genomic] [chromosome=I]
AGCTAGCTAGCTAGCTAGCTAGT
>ref|NC_001134| [org=Saccharomyces cerevisiae] [strain=S288C]
[moltype=genomic] [chromosome=I]
AGCTAGCTAGCTAGCTAGCTAGC

I agree that this issue needs to be resolved, and I will do so as soon as I
can make time. Feel free to follow the progress at
https://github.com/yannickwurm/sequenceserver/issues/145 or send a patch.

-- Priyam

**Comment by yeban** [comment]
See #192.
