### ISSUE TITLE
Error when there's a * in hit sequence.

### ISSUE THREAD

**Issue by yeban** [wurmlab/sequenceserver#188]
Trying to reproduce the issue described at https://groups.google.com/forum/#!topic/sequenceserver/PGAPMssi5I4, I ran into another one.

```
  ArgumentError - invalid byte sequence in UTF-8:
/Users/priyam/sequenceserver/lib/sequenceserver/sequence.rb:197:in `split'
/Users/priyam/sequenceserver/lib/sequenceserver/sequence.rb:197:in `block in run'
/Users/priyam/sequenceserver/lib/sequenceserver/sequence.rb:196:in `each_line'
/Users/priyam/sequenceserver/lib/sequenceserver/sequence.rb:196:in `each'
/Users/priyam/sequenceserver/lib/sequenceserver/sequence.rb:196:in `map'
/Users/priyam/sequenceserver/lib/sequenceserver/sequence.rb:196:in `run'
/Users/priyam/sequenceserver/lib/sequenceserver/sequence.rb:172:in `initialize'
/Users/priyam/sequenceserver/lib/sequenceserver/routes.rb:127:in `new'
/Users/priyam/sequenceserver/lib/sequenceserver/routes.rb:127:in `block in <class:Routes>'
[...]
```

To reproduce:

```
$ mkdir /tmp/test
$ cd /tmp/test
$ echo '>gi|5835987|ref|NP_008750.1|ND6_15094 NADH dehydrogenase subunit 6 (mitochondrion) [Vidua chalybeata]
MMEFVLFLGLLFALGGLAVASNPSPYYGVVGLVVAAIAGGGWLVSLGVSFVSLMLVMVYLGGMLVVFVYS
VSLAADPYPETWTDWGVVGYGFGMGLVVMVGLVVSGVFGLLADVGTVNGAGLLSVRVDFSGAAVLYSEGA
GFLLIGGWGLLLTLFVVLELVRGLSRGAIRAV*' > prot.fa
$ makeblastdb -in prot.fa -dbtype prot -parse_seqids
$ sequenceserver -d .
```

Now BLAST with the same query sequence and try to view sequence or download FASTA.

**Comment by pydupont** [comment]
I solved this bug by patching the run function in lib/sequenceserver/sequence.rb

```ruby
def run
  command = "blastdbcmd -outfmt '%g	%i	%a	%t	%s'" \
            " -db '#{database_names.join(' ')}'" \
            " -entry '#{sequence_ids.join(',')}'"
  
  logger.debug("Executing: #{command}")
  
  out = `#{command} 2> /dev/null`
  @sequences = out.each_line.map do |line|
    line = line.chars.select(&:valid_encoding?).join.encode('UTF-8', :invalid => :replace)
    Sequence.new(*line.chomp.split('	'))
  end
  extend(IO) && write if in_file
end
```

The line:

```ruby
line = line.chars.select(&:valid_encoding?).join.encode('UTF-8', :invalid => :replace)
```

is the only difference. It remove any non utf-8 valid character.

I hope it helps,

Pierre-Yves Dupont

**Comment by yeban** [comment]
Thanks @pydupont. I will verify the fix and try to include it in the next release.

**Comment by billzt** [comment]
How about "*" is in the middle of sequence? Could it work?

**Comment by pydupont** [comment]
Hi,


The star can be at the end only to show that the sequence is an automatic translation. Otherwise it is not a valid IUPAC character.


Pierre-Yves Dupont





On Fri, Aug 28, 2015 at 8:31 AM -0700, "billzt" <notifications@github.com> wrote:












How about "*" is in the middle of sequence? Could it work?

**Comment by yannickwurm** [comment]
thank @pydupont  - @yeban has this been patched?

**Comment by tomas-pluskal** [comment]
It seems this has still not been patched in v. 1.0.6, or am I wrong?

**Comment by yeban** [comment]
@yannickwurm @tomas-pluskal The issue hasn't been patched yet. This is because I am not sure about the fix. 

BLAST accepts both * and - in amino acid sequences and - in nucleotide sequences [1]. We get this error if either of the char is present in the hit sequence being downloaded / viewed. This is because BLAST returns the illegal byte code 255 (0xFF) for both the characters. Further, while BLAST allows U for denoting selenocysteine, it also allows * to appear in the middle of a protein sequence. Thus, @pydupont  and @tomas-pluskal's solution will produce misleading results e.g., sequence 'U-*GFL' will be shown as 'UGFL' and thus cannot be accepted as it is.

An option is to replace the illegal bytes with ? instead of simply swallowing them. It's not the real fix either but will at least prompt the user to double-check the obtained sequence. If we go this road, we should additionally show an error message like is done when retrieving hit sequence with a non-unique id retrieves multiple sequences.

SequenceServer runs blastdbcmd with `-outfmt '%g%i%a%t%s'` option to get the sequence (`%s`) and associated meta data (`%g%i%a%t` - gi, sequence id, accession, title). This gives us control over presentation both in terms of general formatting and normalising NCBI and non-NCBI ids. I would like to note that without the `-outfmt` flag (or `-outfmt '%f' - which returns FASTA by default) blastdbcmd doesn't return illegal unicode byte sequences.

[1]: http://blast.ncbi.nlm.nih.gov/blastcgihelp.shtml

**Comment by yannickwurm** [comment]
In other software (maybe EMBOSS tools),  * are replaced with X

**Comment by tomas-pluskal** [comment]
Just a note: [Transdecoder](https://transdecoder.github.io/) produces peptide sequences ending with * to indicate a stop codon. I think sequenceserver should not show any error/warning message on such sequences, because IMHO there is nothing wrong with such a sequence.

**Comment by yannickwurm** [comment]
agreed

**Comment by tomas-pluskal** [comment]
Hi, 
This issue is still unpatched in v. 1.0.8. Can we have it fixed, please? It is really quite annoying.
Tomas

**Comment by billzt** [comment]
@tomas-pluskal You can see the commit list. Version 1.0.5-1.0.8 did not include any main commits. Perhaps  @yeban should release a new version as soon. Or you could use the master code.

**Comment by yannickwurm** [comment]
This should be detected by doctor #133

**Comment by tomas-pluskal** [comment]
I am not aware what the doctor actually does, but I would like to point out that sequences ending with * should not be rejected or cause any error messages. These are perfectly valid amino acid sequences.

**Comment by tomas-pluskal** [comment]
This bug is still present in version 1.0.9:

````
  ArgumentError - invalid byte sequence in UTF-8:
/home/wenguser/.gem/ruby/2.2.0/gems/sequenceserver-1.0.9/lib/sequenceserver/sequence.rb:197:in `split'
/home/wenguser/.gem/ruby/2.2.0/gems/sequenceserver-1.0.9/lib/sequenceserver/sequence.rb:197:in `block in run'
/home/wenguser/.gem/ruby/2.2.0/gems/sequenceserver-1.0.9/lib/sequenceserver/sequence.rb:196:in `each_line'
/home/wenguser/.gem/ruby/2.2.0/gems/sequenceserver-1.0.9/lib/sequenceserver/sequence.rb:196:in `each'
/home/wenguser/.gem/ruby/2.2.0/gems/sequenceserver-1.0.9/lib/sequenceserver/sequence.rb:196:in `map'
/home/wenguser/.gem/ruby/2.2.0/gems/sequenceserver-1.0.9/lib/sequenceserver/sequence.rb:196:in `run'
/home/wenguser/.gem/ruby/2.2.0/gems/sequenceserver-1.0.9/lib/sequenceserver/sequence.rb:172:in `initialize'
/home/wenguser/.gem/ruby/2.2.0/gems/sequenceserver-1.0.9/lib/sequenceserver/routes.rb:152:in `new'
/home/wenguser/.gem/ruby/2.2.0/gems/sequenceserver-1.0.9/lib/sequenceserver/routes.rb:152:in `block in <class:Routes>'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
/home/wenguser/.gem/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
/home/wenguser/.gem/ruby/2.2.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
/home/wenguser/.gem/ruby/2.2.0/gems/sequenceserver-1.0.9/lib/sequenceserver.rb:92:in `call'
/home/wenguser/.gem/ruby/2.2.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
/usr/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
/usr/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
/usr/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
````

**Comment by yeban** [comment]
I apologise that this issue hasn't been fixed yet. It's a bug in BLAST and I was hoping they would fix it. Given this is still a problem on BLAST 2.5.0+, I will try to include a workaround in the next release. In the meantime, I request you (and others) to use @pydupont's solution.
