### ISSUE TITLE
Next version of BLAST will not include pre-compiled binaries for 32 bit linux systems.

### ISSUE THREAD

**Issue by yeban** [wurmlab/sequenceserver#189]
This will affect automated blast download if we up the minimum version requirement.

**Comment by yeban** [comment]
Looks like 32 bit binaries for linux were retried already with 2.2.31. 2.2.32 onwards macos-universal will be 64 bit only. So we pin the the next release of SS to 2.2.32 and remove the 32 bit linux downloader.

**Comment by yannickwurm** [comment]
please ensure that the 95% of people with older systems will know how to access the old version of seqserv which supports pre 2.2.31 BLAST
