### ISSUE TITLE
xdg-open nuisance

### ISSUE THREAD

**Issue by yeban** [wurmlab/sequenceserver#195]
https://groups.google.com/forum/#!topic/sequenceserver/uuFF6l0Yheo

**Comment by yannickwurm** [comment]
I vote to kill this "feature" as it introduces a usability bug.

**Comment by terfn** [comment]
For some reason this gets fixed for me when I replace
```ruby
 `xdg-open #{server_url}`
```
with 
```ruby
 system "xdg-open #{server_url}"
```
From what I read both invoke a new process but the first one returns the output and the second returns the exit code. Perhaps the first one makes it hang because SS is waiting on the output. Not sure how this will work on other platforms

**Comment by yeban** [comment]
That has to be it - brilliant! Could you send a PR?

**Comment by yeban** [comment]
Note: Could try `spawn` if this doesn't fix it completely.
