### ISSUE TITLE
Display hit coordinates in results and optionally add a link to copy them.

### ISSUE THREAD

**Issue by yeban** [wurmlab/sequenceserver#198]
https://groups.google.com/forum/#!topic/sequenceserver/Pi39__s77uk

**Comment by billzt** [comment]
@yeban Well, I hope to make a workaround by myself before new version come out. How to obtain the hit coordinates in Ruby? ^_^

**Comment by yeban** [comment]
Thanks to @terfn we have a `coordinate` method that you can call in link generator methods. Unfortunately, this method will be available only in the next release (difficult to say when :/). For now you can reuse the same logic (https://github.com/wurmlab/sequenceserver/blob/master/lib/sequenceserver/blast/hit.rb#L48) in a link generator method though.

If you can find the time, do send us a pull-request for this :).

p.s: Sorry I couldn't respond sooner ... was away last week.

**Comment by yeban** [comment]
Closing because it only makes sense when searching genomes and SequenceServer doesn't currently distinguish between different type of nucleotide sequences. A user would have that information and can accordingly implement either a link to the genome browser or just display the coordinate so it is easily copyable.
