### ISSUE TITLE
Downloading FASTAs and reports is broken.

### ISSUE THREAD

**Issue by ilevantis** [wurmlab/sequenceserver#203]
Currently unable to download a tabular or XML report, or any of the potential fasta files from the results page of a BLAST search.
Example message on trying to download:
```
Not Found: /download/sequenceserver_blast_result20150917-28893-1luwfkv.xml
```

**Comment by ilevantis** [comment]
This may be specific to Fourmidable.

**Comment by yeban** [comment]
It's specific to Fourmidable.
