### ISSUE TITLE
List of "Sequences producing significant alignments" should be collapsable

### ISSUE THREAD

**Issue by ilevantis** [wurmlab/sequenceserver#204]
The linked list / table of contents that appears just after the alignment visualisation should behave in the same way as the visualisation. 

It should show only the top 20 in the list unless a "show more" button is clicked. Otherwise long lists take an annoying amount of time to scroll through.

**Comment by yeban** [comment]
An alternative could be to have the rows clickable to reveal hit details instead of a separate table and list of hit details.

**Comment by yeban** [comment]
Fixed
