### ISSUE TITLE
Paramaters for a BLAST search should be displayed on the results page

### ISSUE THREAD

**Issue by ilevantis** [wurmlab/sequenceserver#205]
The parameters used in the BLAST search should be displayed somewhere on the results page.

**Comment by yeban** [comment]
It's in master already (needs some prettification though). Will be available in next release.

**Comment by yeban** [comment]
I think BLAST's XML doesn't include user supplied parameters from advanced params input field - only the BLAST defaults. SequenceServer should merge user supplied params to those parsed from XML and display them all on the reports page.

/cc @terfn
