### ISSUE TITLE
Blast job hangs

### ISSUE THREAD

**Issue by terfn** [wurmlab/sequenceserver#208]
Noticed this when working on issues.

Most times when I run SS locally and paste in a simple query, and the job tab just hangs there. When I refresh the page, the job gets done. This is clear from command line output too, I made it log the commands and the first time it prints nothing, after refresh it starts to log the commands.

Could just be something with my local setup, I’m only posting this in case anyone else has the same problem.

**Comment by yeban** [comment]
Can you post me a screenshot, with the debug console open ... before refreshing the results page.

**Comment by terfn** [comment]
<img width="1492" alt="screen shot 2015-09-20 at 18 08 46" src="https://cloud.githubusercontent.com/assets/6852065/9981939/61f12cb2-5fc3-11e5-81af-cf6608be4529.png">
I get this on some fourmidable data. It happens when I blast a query from ncbi acromyrmex echinatior genomic against itself for other formicidae genomes. Doesn't happen with outgroups or transcriptomes. I guess these jobs take longer than the others so it might cause something to go wrong there?
