### ISSUE TITLE
Issues with deploying SequenceServer on subURI

### ISSUE THREAD

**Issue by terrymun** [wurmlab/sequenceserver#216]
After combing through the forums and the web for instructions, I have managed to install sequence server on a server I am working on. My server setup:

```
Server version: Apache/2.4.6 (Red Hat Enterprise Linux)
Server built:   Aug 10 2015 07:39:34
```

However, I seem to have ran into a hitch about how to deploy it with Apache. I was given these lines after installing SequenceServer:
```
LoadModule passenger_module /root/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/passenger-5.0.20/buildout/apache2/mod_passenger.so
<IfModule mod_passenger.c>
    PassengerRoot /root/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/passenger-5.0.20
    PassengerDefaultRuby /root/.rbenv/versions/2.1.0/bin/ruby
</IfModule>
```

...which I have placed in the `httpd.conf` file in the `/etc/httpd/conf/` directory.

With regards to my system setup, my document root is located at `/var/www/html`  and I am intending to deploy SequenceServer as a subfolder, i.e. at `/var/www/html/sequenceserver` (or `http://[...]/sequenceserver`). I have retrieved the public path of SequenceServer and created a symlink in the document root:

```
ln -s /root/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sequenceserver-1.0.4/public sequenceserver
```

I have verified that the path is correct and the `/public` directory does exist.

I then updated the `httpd.conf` again, this time to enable subURI deployment:

```
# Sequence server
<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /var/www/html
    <Directory /var/www/html>
        Allow from all
        Options -MultiViews
        Require all granted
    </Directory>

    Alias /sequenceserver /root/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sequenceserver-1.0.4/public
    <Location /sequenceserver>
        PassengerBaseURI /sequenceserver
        PassengerAppRoot /root/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sequenceserver-1.0.4
    </Location>
    <Directory /root/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sequenceserver-1.0.4/public>
        Allow from all
        Options -MultiViews
        Require all granted
    </Directory>
</VirtualHost>
```

And I am stuck with a 403 forbidden error—even when I attempt to access the contents of the `css` or `js` subfolders of `/public`. Any idea why this is happening?

**Comment by terrymun** [comment]
Looks like the issue is resolved when I used `chmod +x root` ;)

**Comment by yeban** [comment]
Right. Also, consider running SequenceServer (and any web app in general) as a normal user instead of root.

**Comment by terrymun** [comment]
Is there any way I can (forcibly) run SequenceServer as a user? So far I have access to the server as the root user and there are no other users on it.
