### ISSUE TITLE
BLAST+ binaries not found

### ISSUE THREAD

**Issue by terrymun** [wurmlab/sequenceserver#217]
I have managed to install SequenceServer and have the app running. However, it seems like SequenceServer has failed to find the BLAST+ binaries:

<img width="1321" alt="screen shot 2015-09-27 at 11 49 23" src="https://cloud.githubusercontent.com/assets/5593067/10122147/380d2f7c-650e-11e5-9dbf-a09c486ef3eb.png">

```
Web application could not be started
Could not locate BLAST+ binaries. (SequenceServer::BLAST_NOT_INSTALLED)
```

That is odd because when I checked the `~/.sequenceserver.conf` file, the directory has been specified:

```
:num_threads: 1
:port: 4567
:host: 0.0.0.0
:bin: "/root/.sequenceserver/ncbi-blast-2.2.31+/bin"
:database_dir: "/var/blast/db"
```

And `cd`ing into the bin directory reveals that all binaries are intact:

```
blastdb_aliastool  blastn             deltablast       makembindex    rpstblastn  update_blastdb.pl
blastdbcheck       blastp             dustmasker       makeprofiledb  segmasker   windowmasker
blastdbcmd         blastx             legacy_blast.pl  psiblast       tblastn
blast_formatter    convert2blastmask  makeblastdb      rpsblast       tblastx
```

I have tried to execute the any of the binaries in there, and they run just fine. Is there a reason why SequenceServer is failing to find the BLAST+ binaries?

**Comment by yeban** [comment]
Maybe because SequenceServer is being run as different user from the command line and from Apache. ~ always expands to the home directory of the user the app was run as. Maybe `~/.sequenceserver.conf` actually is `/home/terrymun/.sequenceserver.conf` when it should be `/root/.sequenceserver.conf` in your setup.

If that's indeed the case, you could resolve this by moving `.sequenceserver.conf` to `/root`.

**Comment by terrymun** [comment]
Thanks for the reply @yeban. Using `find / -name *sequenceserver.conf` I have only found one copy of the file, and it's absolute path is `/root/.sequenceserver.conf`. I have always been using the root user, even though there is indeed a user created under my name—`cp`ing the file to `/home/terry/.sequenceserver.conf` did not make the error go away.

A possible issue is that SequenceServer is being run with `nobody`:

```
User and groups
uid=99(nobody) gid=99(nobody) groups=99(nobody)
Environment variables
PATH = /root/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
LANG = C
NOTIFY_SOCKET = @/org/freedesktop/systemd1/notify
PASSENGER_USE_FEEDBACK_FD = true
SERVER_SOFTWARE = Apache/2.4.6 (Red Hat Enterprise Linux) PHP/5.4.16 Phusion_Passenger/5.0.20
PASSENGER_DEBUG_DIR = /tmp/passenger.spawn-debug.XXXXPup2Vf
USER = nobody
LOGNAME = nobody
SHELL = /sbin/nologin
HOME = /
PWD = /root/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sequenceserver-1.0.4
IN_PASSENGER = 1
PYTHONUNBUFFERED = 1
NODE_PATH = /root/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/passenger-5.0.20/src/nodejs_supportlib
RAILS_ENV = production
RACK_ENV = production
WSGI_ENV = production
NODE_ENV = production
PASSENGER_APP_ENV = production
RAILS_RELATIVE_URL_ROOT = /sequenceserver
RACK_BASE_URI = /sequenceserver
PASSENGER_BASE_URI = /sequenceserver
UNIQUE_ID = Vgjsma@WN78PZSxCDMCYyQAAAAI
GEM_PATH = /root/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0:/.gem/ruby/2.1.0
GEM_HOME = /root/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0
BUNDLE_BIN_PATH = /root/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/bin/bundle
BUNDLE_GEMFILE = /root/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sequenceserver-1.0.4/Gemfile
RUBYOPT = -rbundler/setup
RUBYLIB = /root/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/lib
```

Is there anyway to force SequenceServer to be initialised under a specific user? 

My other question is that: when the SequenceServer app is initialised via Passenger, does it still use the `.conf` file, or does it rely on the `.yml` files that were being talked about in other discussions? If so, where should they be?

**Comment by terrymun** [comment]
**Update**

After reading through Phusion Passenger's documents, I realised I can force Passenger to run app with a certain user. Seems to be fixed now, by using `PassengerUserDefault terry` in the server config context and `PassengerUser terry` in the virtual host/directory context.

However, my attempts to build using the `rake` command has failed:

```
/root/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sequenceserver-1.0.4/lib/sequenceserver/blast/report.rb:37:in `generate': undefined method `root' for nil:NilClass (NoMethodError)
```

p/s: I have learned a lot on how to setup SequenceServer, and thanks for your help! I am thinking of penning a thorough guide to setting up SequenceServer, because I find that the documentation a bit lacking in that sense (but a good place to start, of course). What do you guys reckon?

**Comment by yeban** [comment]
A thorough guide to setting up SequenceServer with Apache+Passenger would be great! I will be happy to include it in the website - ours has grown a bit outdated, and difficult for me to keep up to date as I don't use this setup anymore.

For version 1.0.4 `rake` only runs the test suite (this has changed in the master and will be reflected in the next release, where rake first runs the test suite and then build the JS). Is this what you want? Not sure, maybe the error you indicate is due to `~/.sequenceserver` directory not being present.

Whether run from the command line or via Passenger, SequenceServer looks for `~/.sequenceserver.conf`. This can be changed with the `-c` flag in command line and via config.ru for Passenger by modifying the `SequenceServer.init` line to `SequenceServer.init(:config_file => "/path/to/config/file")`.

**Comment by terrymun** [comment]
Alright, I will start working on it soon—before I forget everything. I have to admit that I have almost no experience in setting up Ruby on Rails and Fusion, so the guide might be overcomplicated—but just trim out the parts you think is redundant or unnecessary.

I can see that `rake` is failing in the current build. Since I can't build it with `rake`, I looked at the readme.md of [an older release which passed the build test](https://github.com/wurmlab/sequenceserver/tree/6de0ac561c828c6e96e36b9b1f08eee9108534a9), and realised I can simply use:

```
npm run-script cop
npm run-script build
```

Somehow these instructions were lost in a recent commit ;) 

Also, I have finally managed to get SequenceServer up and running. Documentation is a bit lacking on locating the configuration files and how we can force SequenceServer to use a specific one when launched via Passenger, but your answer solved my issue :) 

p/s: Would you guys be interested in looking at implemented a non-greyscale colour scale for the match? I have made some modifications and could submit a pull request if that's alright.

**Comment by yeban** [comment]
Thanks @terrymun. I'm looking forward to the doc! Don't worry about it being too detailed - put in everything you had to figure out. We will then revise it.

The instructions to build JS aren't really lost. We are ahead of 1.0.4 in the repo. Amongst other things, I changed `rake` to test, lint, and build (both JS and the gem) at once. Since you are using 1.0.4, you should indeed be seeing 1.0.4's (the older) readme :).

There's talk about using NCBI's colour scheme in the graphical overview here #218. I'm more inclined towards gradient, but perhaps some code and a screenshot may change that (and the opinion of others).

**Comment by terrymun** [comment]
D3 is pretty flexible in the sense that we can use a threshold (which falls inline with how NCBI separates the different scoring groups, although we are using E-value instead of score), or we can use the log gradient (which is already implemented). The only thing is to add a wrapper around `gradScale` (in `graphicaloverview.js`) so that it will map to a range of colours—and I think colorbrewer has a very good list of colours we can work with :) 

As attached in a screenshot of a new colour scheme I am working with. I have made some corrections to the scaling function because an e-value of `0.0` does not map very well in a logarithmic scale ;) 

![screen shot 2015-10-01 at 10 59 43](https://cloud.githubusercontent.com/assets/5593067/10216746/929eaf40-682b-11e5-82e5-e32810ccd122.png)

**Comment by yannickwurm** [comment]
Thanks Terry - this looks cool - but RED_GREEN COLOR BLINDNESS!  (~10% of males?)

Furthemore, I find it counterintuitive that the yellow (which is less dark than either of the extremes) is in the middle. If you look at the graph without actively looking at and  interpreting the gradient scale, you'd think the short hit is the weakest. If you were to print it out in b/w you'd be even more confused.

So I like the idea of potentialy using e.g. a 3-color scale but we have to be very careful that the gradient isnt contradicting itself.

Black to blue to orange to light orange is the kind if thing that might work.   (increasing in lightness AND in vibrance as you go along the scale (I'm probably using the wrong words here))

**Comment by terrymun** [comment]
That's true—but there are other color scales to choose from. I'm not very familiar how module building works, but we can always allow users to configure which color scale they can use. Color Brewer has a few scales that are black and white and colorblind friendly ;) I am simply demonstrating that using a colour scale might work better than a black-white one. 

What's your take on the threshold colour scale instead of a graduated one?

**Comment by yeban** [comment]
@terrymun I recently made a few updates to the website and was wondering if you were able to work on the manual?

**Comment by terrymun** [comment]
@yeban I have written it down somewhere, but I'm afraid it is a bit too specific... would it do more harm than good?

**Comment by yeban** [comment]
Maybe I could use it as a starting point? (my email address is in the README)

**Comment by terrymun** [comment]
Will do! The work server is current down for weekend maintenance (of course, Murphy's Law!), but I'll send you a copy on Monday :+1: thanks again for all the work—really appreciate how much SequenceServer makes BLASTing a lot easier :) 

p/s: Folks at my lab also would love to send their regards. They've been stuck on the NCBI server for years... and never really liked it.

**Comment by yeban** [comment]
Sweet. Thanks :)
