### ISSUE TITLE
Use color key for alignment scores similar like NCBI public blast server 

### ISSUE THREAD

**Issue by billzt** [wurmlab/sequenceserver#218]
The color key used now by sequenceserver looks like this: Dark gray => Light gray (Difficult to distingush!)

![a](https://cloud.githubusercontent.com/assets/1146090/10129019/3714dba4-65ec-11e5-8750-37a5435b00d6.JPG)

The color key used by NCBI public blast server  looks like this: Red => Pink => Green => Blue => Dark (Easy to distinguish!)
![b](https://cloud.githubusercontent.com/assets/1146090/10129047/87f42a2a-65ec-11e5-97bb-d0e59095296c.JPG)

How about change to this new  color key ?

**Comment by vivekiitkgp** [comment]
Hey @billzt, There is a major  difference between NCBI's graph and Sequenceserver's graph. That is, color coding on NCBI is given by the score of the hits obtained, while Sequenceserver colors them based on the expect value.

Now there are two ways to interpret your question. Do you wish to change the color to distinguish it better or do you want the graphical scheme as that of NCBI's?

**Comment by billzt** [comment]
@vivekiitkgp Well, I just wish to change the color to distinguish it better. Dark gray => Light gray seems too difficult to distinguish. ^_^

**Comment by vivekiitkgp** [comment]
@billzt Heh okay! I'll describe here a few things and by making those changes locally (in respect to your choices) you should see the updates.

The code for graphical overview resides in `public/js/graphicaloverview.js`. There in, the two important locations where this color scheme is decided are - [L282-L294](https://github.com/wurmlab/sequenceserver/blob/master/public/js/graphicaloverview.js#L282-L294) and [L332-L334](https://github.com/wurmlab/sequenceserver/blob/master/public/js/graphicaloverview.js#L332-L334). The former is a function which takes an expect value and maps it to a range `[40, 150]`, and latter simply colors the hsps by passing RGB values to `d3.rgb()`.

Currently, we simply generate a number in the range `[40, 150]` and pass the same number as R, G as well as B value giving a grey-white color scheme. So, if you just want red, simply pass 0 to G and B values in `d3.rgb()` function in L332.

With this knowledge, you can use any color combination you want.

You, however, still need to change the legend colors which can be done at lines [L174-L176](https://github.com/wurmlab/sequenceserver/blob/master/public/js/graphicaloverview.js#L174-L176).  The offsets along with the percentage denote the color to be used at left (0%), mid (50%) and right (100%) to generate the gradient.

Let me know how it goes.

**Comment by yeban** [comment]
Would it suffice if SequenceServer's legend indicated the range of evalues that correspond to a particular shade? One can surely memorise NCBI's color code, but I don't see how it's more intuitive than a gradient to instantly infer relative strength of hits.

**Comment by yannickwurm** [comment]
Adding numbers (and tickmarks) to the gradient scheme is a good idea

**Comment by yeban** [comment]
see #301
