### ISSUE TITLE
Some minor improvements are needed for the result page

### ISSUE THREAD

**Issue by billzt** [wurmlab/sequenceserver#219]
In current stable version, the result page list five columns: Number, Sequences, Total score, E value and	"Length" 

![c](https://cloud.githubusercontent.com/assets/1146090/10129193/103ce02e-65ee-11e5-9dee-867e3421b5dc.JPG)

(1) The word "Length" is ambigous, Hit Length or Alignment Length? It isn't clear until following detailed alignments were manually viewed. This could be modified as "Hit Length".

(2)  Alignment Identities could be listed, just like the NCBI public blast server.

(3) Is it possible to show alignments in color schemes like  legacy wwwblast? (https://www.cottongen.org/tools/ncbi_blast/frame/docs/color_schema.html). Like this:
![d](https://cloud.githubusercontent.com/assets/1146090/10129371/e19518d4-65ef-11e5-9118-b3a061a5b468.JPG)

**Comment by yeban** [comment]
Thanks @billzt. These are valuable input. Color coding alignments is not possible at the moment, but I think @alekhyam94 is working on making this possible. The color scheme will likely be inspired from more than wwwblast - we will also consider what BioJS and related projects are doing in this regard.

**Comment by yannickwurm** [comment]
Changing "Length" to "hit length" should be trivial :)

**Comment by yeban** [comment]
see #300 for 3
