### ISSUE TITLE
Feature request: Dockerization of Sequence Server

### ISSUE THREAD

**Issue by ajmazurie** [wurmlab/sequenceserver#221]
Sequence Server is a very nice software but its installation requires a whole interpreter (Ruby) and associated libraries. I'd be interested to know if there is any plan to dockerize the project, so that people could deploy the software anywhere with just one command.

Best,
Aurélien

**Comment by yeban** [comment]
Thanks for the kind words and the feedback @ajmazurie. I would like to note that Ruby is available on Mac by default and is a one-line-install on Linux distributions from the respective package manager. Everything else is built-in or automatically installed by SequenceServer. The only issue with respect to external packages is #197, which is only a problem if you are using Ruby 1.8.7.

I am not sure how much dockerisation will really simplify installation. You will still have to install docker. And given that SequenceServer reads from and writes to the local filesystem, you will also have to make way for accessing local filesystem within the container, which is a pain on the Mac and on SELinux based Linux distros. Then as far as deployments are concerned, securing a docker setup is quite involved as far as I understand (thanks to docker running as root).

Thus I doubt the benefit dockerisation will bring to the project. If anything, I only see it as increasing the maintenance burden of troubleshooting docker related issues. Personally, I would like to build a deb package and request inclusion in BioLinux ppa than distribute docker images. Other devs may differ.

**Comment by yannickwurm** [comment]
Thanks Aurélien. What kind of application context do you suggest? ie would this be for a process on a personal computer, or compute cluster? or a cloud?

@yeban how about this: 
 1. A generic sequenceserver dockerfile exists.  
 2. person X decides they want a seqserv with NCBI-nr version XXX. For that they create a new dockerfile that derives from the generic sequenceserver docker file but adds the lines necessary to download (and potentially build) the relevant database
 3. When needed, that new dockerfile could be (instantly) deployed on a server with a cloud service such as Deis. 

@ajmazurie I'd like to add that we would look upon a pull request very favorably. Probably easiest is to take a simple linux, apt-get install ruby 2, then gem install sequenceserver...

**Comment by ajmazurie** [comment]
Hi, I'm thinking of environments that already use Docker to deploy various software on multiple machine; e.g., compute clusters where you want the exact same software (and dependencies) everywhere. That's what we want to do in our university.

Plus, as you rightly mention Docker makes it very easy to customize applications without having to worry about actually installing these applications.

I'll probably just create a Sequenceserver Dockerfile in the near future, and do a pull request; I just don't have the time to do it right now.

Aurélien

**Comment by yeban** [comment]
closed via #241
