### ISSUE TITLE
Travis failing

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/sequenceserver#222]
its ok for development version (master) to fail, but seeing a red "failing" button here or on biogems can be discouraging to potential users. 

Thus biogems should indicate travis status of  latest release branch; the readme could include both (clearly separating what is stable from dev)...

**Comment by yeban** [comment]
Just realised that #223 (and follow-up) is not going to auto-resolve badge issue in README or on biogems.info.

/cc @vivekiitkgp

**Comment by yeban** [comment]
The branch will have to be specified in the badge's URL. Easy to do in the README. Dunno how to do it for biogems.

**Comment by yeban** [comment]
Fixed in README. Discusssing this on biogems: https://github.com/pjotrp/biogems.info/issues/83

**Comment by yeban** [comment]
It's done.
