### ISSUE TITLE
Pipe in sequnces ids.

### ISSUE THREAD

**Issue by yeban** [wurmlab/sequenceserver#225]
The following seqid trips sequence retrieval: `PWVi6_TR80574|c0_g1_i1`.

Corresponding mailing list thread - https://groups.google.com/forum/#!topic/sequenceserver/wqKTcpo7qIc

**Comment by jorvis** [comment]
+1 on the importance of fixing this.  I'm running into it also with identifiers assigned by [Trinity](https://github.com/trinityrnaseq/trinityrnaseq/wiki)

**Comment by jorvis** [comment]
I've tried to implement a temporary fix by replacing the call to blastdbcmd in 'sequenceserver-1.0.8/lib/sequenceserver/sequence.rb' with a different utility which actually extracts the sequence correctly.  But I don't see the change evident in the server, even after restarting sequenceserver.  I'm pretety unfamiliar with Ruby.  How do I rebuild so my modification takes effect?

**Comment by yeban** [comment]
Editing server code doesn't require any rebuilding - just need to restart server. I can take a look at the code if you want. Can you open a pull-request?

**Comment by yeban** [comment]
This is no longer an issue in SequenceServer 1.1.0-beta using BLAST 2.6.0+.
