### ISSUE TITLE
Website & documentation.

### ISSUE THREAD

**Issue by yeban** [wurmlab/sequenceserver#228]
**Documentation**
- [x] Plugin & link-generator documentation needs to be exhaustive.
- [x] Apache+Passenger documentation needs updating / rework.
- [x] Add a section on deploying to HPC.

**Other stuff**
- [x] Headings have too much top and bottom padding.
- [x] All except basic setup (like the documentation above) should move to other pages.
- [x] PNG/GIF of setup process?

**Comment by terrymun** [comment]
For Apache+Passenger documentation, I have published an article/tutorial on how to set it up on a web server and serve it off a subdirectory. Let me know if you need further clarifications :) https://medium.com/coding-design/setting-up-sequenceserver-edf9d992998c

**Comment by yannickwurm** [comment]
I'm not a fan of fragmenting stuff between multiple pages: reduces googlability AND the ability to search with control-F

**Comment by yeban** [comment]
We need to keep home page simple, Y. Also we get better analytics: how many came to view documentation and which documentation, etc.

**Comment by terrymun** [comment]
With regards to installation instructions, you guys can check out the method used by GitLab—they have a drop down selection of server OSes, and will dynamically display the appropriate installation instructions. Not sure if SequenceServer can run on NGINX tho :)
