### ISSUE TITLE
New Reports Page Bugs

### ISSUE THREAD

**Issue by terfilip** [wurmlab/sequenceserver#229]
report.js doesn't get properly loaded first time I run the page, and clicking on FASTA of all hits results in a request to /undefined. Then going back suddenly lets the report.js be loaded and it works fine.

Will add more bugs on the reports page here as I find them.

**Comment by yeban** [comment]
From the top of my head:
- Kablammo needs to be responsive, like graphical overview.
- sequence viewer links work only after page load.

**Comment by IsmailM** [comment]
Another new Reports Page bug - Sidebar links need to be disabled (or fully greyed out) until that BLAST results load fully. Clicking on the Sidebar links before the BLAST results are produced causes the following error:

```
Argument Error - Database id should be one of: cceba041efceb36c84cc5067938a0e89
```

**Comment by yeban** [comment]
I think sidebar shouldn't be shown at all until the results are fully loaded.
