### ISSUE TITLE
Error: Server didn't respond

### ISSUE THREAD

**Issue by billzt** [wurmlab/sequenceserver#233]
When I blast a protein sequence to a large database (NCBI nr database), after submitting sometime, it occures error:  Server didn't respond

![default](https://cloud.githubusercontent.com/assets/1146090/11808712/21cb03b4-a35d-11e5-8d45-991afe69ae64.PNG)

In fact, the blastp process is still running in background.

My Platform: apache 2.2.15 +  passenger 5.0.18 on CentOS 6. Previously it works well. I'm not sure whether it was due to system update or network instance.

**Comment by yeban** [comment]
Looks like you need to change timeout setting in Apache/Passenger.

**Comment by yeban** [comment]
Also, I would like to note that we won't have to worry about server timeout from the next release as the behaviour has changed to polling for results. (note to self: close this issue when 1.1 is released)

**Comment by yeban** [comment]
I have documented this on website for now.
