### ISSUE TITLE
How do you  handle blast warning

### ISSUE THREAD

**Issue by kaiwang0112006** [wurmlab/sequenceserver#236]
Hi, this is a curious question from a developer. I noticed that you throw blast program error to user. But blast also have warnings like: "/lib64/libz.so.1: no version information available". This kind of warning is different from error and can be ignored. How can you separate them?

**Comment by yeban** [comment]
If exit status is not 0, it's an error not a warning. We parse and try to show the exact error from stderr but other details (warnings and such) may skip out to user.
