### ISSUE TITLE
How about "select" database instead of click

### ISSUE THREAD

**Issue by billzt** [wurmlab/sequenceserver#240]
In the current UI, database lists are chosen by multiple checkbox. This would become extremely ugly if a large number of database were available. How about add a configure option to use "select" instead of  "check"?

**Comment by yannickwurm** [comment]
you mean radio buttons? I'm having difficulty visualizing what you mean?

**Comment by billzt** [comment]
@yannickwurm No, I mean <select></select> list.

**Comment by yeban** [comment]
Probably not. Select is ugly by default, be it one item or multiple. And it is not intuitive to hold Cmd/Ctrl to select multiple values. If you mean ugly at a functional level, other options (like #29) should be explored.

**Comment by guyleonard** [comment]
For a quick and dirty hack I include a select all button like this:

In search.erb:

Add this to the bottom of the file, just below the  section
  
```
  <script>
  $(function(){
      $('#checkAll').on('change', function(){
         var others = $(this).parent().find('input[type="checkbox"]').not(this);
         var value  = !!this.checked;
         others.prop('checked', value);
      });
  });
  </script>
```
and also in the same file, line 204? Add this after the </div> and before the <ul tag...

`<input type="checkbox" id="checkAll" /> Select All Databases<br />``

**Comment by bordin89** [comment]
@guyleonard I tried your approach, but I was wondering if the comment you made was incomplete. 
Would you be so kind to point out where I'm wrong? Thanks!
I put the code you provided at the bottom of the page and the I modified the portion of the code to add the button. 

```
<div
        class="form-group databases-container">
        <%# sort => same ordering of nucleotide and protein datbases %>
        <% databases.keys.sort.each do |type| %>
          <div
            class="<%= databases[(databases.keys - [type]).first] ? 'col-md-6' : 'col-md-12' %>">
            <div
              class="panel panel-default">
              <div
                class="panel-heading">
                <h4><%= type.capitalize %> databases</h4>
              </div>
                <input type="button" name="checkAll" id="checkAll" />
                <ul
                class="list-group databases <%= type %>">
                <% databases[type].sort_by(&:title).each do |database| %>

                <li class="list-group-item">
                    <div
                      class="checkbox">
                      <label>
                        <input type="checkbox" name="databases[]" value="<%=database.id%>" data-type="<%=database.type%>" />
                        <%= database.title or database.name %>
                      </label>
                    </div>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
```

**Comment by guyleonard** [comment]
There does seem to be something missing from my original post! It should read as this:

`<input type="checkbox" id="checkAll" /> Select All Databases<br />`

**Comment by bordin89** [comment]
@guyleonard It seems to work, but only on the first column (Nucleotide), not on the protein databases.

This is my website just in case.

http://pvcbacteria.org/blast/

**Comment by bordin89** [comment]
I was able to fix the problem. This is the code that works with both columns. 

<input type="checkbox" class="checkAll" /> Select All Databases<br />

$('.checkAll').on('change', function(){
         var others = $(this).parent().find('input[type="checkbox"]').not(this);
         var value  = !!this.checked;
         console.log("hi");
         others.prop('checked', value);
      });

**Comment by yeban** [comment]
So changing '#' to '.' worked?

**Comment by bordin89** [comment]
It worked using a class instead of a fixed id. Now it works on both columns.
