### ISSUE TITLE
Error when selecting the database before dropping an input file (on Master branch)

### ISSUE THREAD

**Issue by IsmailM** [wurmlab/sequenceserver#245]
If you select a database _before_ dropping an input file into the browser, the 'Drop query sequence file here' modal does not automatically close and remains open and as such, you are unable to proceed further.

On the hand, if I select the database _after_ dropping the input file into the browser, SS works as expected...

In the JS console, I see the following JS error, which is probably causing the error. 

<img width="785" alt="web_inspector_ _localhost" src="https://cloud.githubusercontent.com/assets/5578375/13741314/7f659596-e9cd-11e5-81bb-724fa31a5253.png">

In a related or separate issue, I see the following React warning:

```
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of Databases. See https://fb.me/react-warning-keys for more information.
```

Note this is on the Master Branch…

**Comment by aniarya82** [comment]
![screen shot 2016-05-18 at 8 00 25 pm](https://cloud.githubusercontent.com/assets/7463217/15362568/4160763c-1d33-11e6-8c11-78af0c82a4ee.png)
I also face similar problem dragging and dropping files.

**Comment by yeban** [comment]
This doesn't seem to be an issue anymore
