### ISSUE TITLE
Circos visualisation.

### ISSUE THREAD

**Issue by yeban** [wurmlab/sequenceserver#247]
I think we shouldn't pre-generate and embed circos visual within HTML results. Should be able to select hits and download circos for those. The query to which the selected hits match should be automatically included in the visual and relationship of a hit to each query should be clearly shown.

I don't know if we should emit PNG or the karyotype and links file and let users build PNG themselves. Former is simpler for users, but the latter might be desirable to leverage advanced customisation offered by circos and to make suitable tradeoffs regarding build time and level of detail in the visual. I am inclined towards the latter.

**Comment by yeban** [comment]
There's also BioCircos.js -  http://bioinformatics.oxfordjournals.org/content/early/2016/02/13/bioinformatics.btw041.abstract. If it works, we could consider embedding circos directly in HTML results.

**Comment by yannickwurm** [comment]
wouldn't this be redundant with kablammo?

**Comment by yeban** [comment]
I don't think so. Kablammo is for 1 hit & query pair. With circos we can show relationship between single query multiple hits as well as multiple query multiple hits at once.

**Comment by yannickwurm** [comment]
makes sense

**Comment by vivekiitkgp** [comment]
@yeban I am not sure if a circos graph is usually drawn in that way.

Usually, the items on the circumference are of one type and then you connect those items to each other based on a relationship. So, either we can have all the queries on the boundary and then link them based on *shared hits*(or something similar, *interesting* observations), or list all the hits/hsps on the boundary and link them with a relation that is the property of the queries.

I am not sure how or what can I infer from the rough sketch graph you have shown. Would you elaborate a bit, please?

**Comment by yeban** [comment]
Not surprisingly, circos type visualisations can be created with D3 as well:

1. http://bl.ocks.org/mbostock/4062006
2. http://www.delimited.io/blog/2013/12/8/chord-diagrams-in-d3

And there's [CircosJS](https://nicgirault.gitbooks.io/circosjs/content/index.html) built on top of D3.

**Comment by yeban** [comment]
So we went ahead with CircosJS to generate a summary of 25 most significant alignments (by evalue), embedded at top of results page. Customisation is not possible - user should tweak BLAST params to get the most relevant results of which a circos summary will be shown.

Further improvements required:
- [ ] Ribbons can be untangled further. Ideally CircosJS or d3 should have a simple way to take care of it. If not, we can layout as Query1 -> hits for query 1, Query2 -> hits for query 2, so on; making sure identical hits for different queries are not repeated in the visualisation.
- [ ] Ribbons should be interactive: highlight them on hover or click (like Kablammo) and place tooltip to indicate alignment statistics.
- [ ] Further, the ribbons should be twisted to indicate strandedness.

- [ ] Colour scheme for ribbons should indicate significance of the alignment: red, orange, yellow, blue in the order of increasing significance. Along with a legend.

- [ ] Use smaller font-size (8-10 px / <=12 px) for both ticks and labels.
- [ ] Length should be indicated as the last tick for each karyotype.
- [ ] Set minimum length for karyotypes as 35 px.
- [ ] Tooltip for karyotypes are oddly positioned.
- [ ] Centre the plot.
