### ISSUE TITLE
database order in front-end page

### ISSUE THREAD

**Issue by billzt** [wurmlab/sequenceserver#258]
By deault, the order of databases are sorted by name in alphabet, like this:

![default](https://cloud.githubusercontent.com/assets/1146090/14407851/f6ff1a26-ff0a-11e5-9e5b-48550297ba8b.PNG)

Is it possible to arrange them in a customized way?

**Comment by yeban** [comment]
You can tweak [search.erb](https://github.com/wurmlab/sequenceserver/blob/1.0.x/views/search.erb#L206) to get the desired result.
