### ISSUE TITLE
BLAST Database error: Could not find volume or alias file (.nal) referenced in alias file (-).

### ISSUE THREAD

**Issue by jcastrof** [wurmlab/sequenceserver#259]
Hello,

I just updated Sequence Server to version 1.0.8 and I got this message when I tried to run 

Error:
BLAST Database error: Could not find volume or alias file (.nal) referenced in alias file (-).

I hope there is a solution for this.

Thanks

**Comment by yeban** [comment]
Which version did you upgrade from? Do you get this error when starting SequenceServer or running a BLAST search?
