### ISSUE TITLE
warning explicit require 'tilt/erb'

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/sequenceserver#262]
`gem update`
`gem install sequenceserver`
`sequenceserver`
`[....]`
`    WARN: tilt autoloading 'tilt/erb' in a non thread-safe way; explicit require 'tilt/erb' suggested.`

**Comment by yeban** [comment]
It's Sinatra autoloading `tilt/erb`, not us. Explicitly requiring `tilt/erb` in our code could make the warning go away though. Not a big deal.

**Comment by terrymun** [comment]
👍
