### ISSUE TITLE
How to view the commands executed by sequenceserver

### ISSUE THREAD

**Issue by billzt** [wurmlab/sequenceserver#267]
I encounter a strange problem: using the exactly same query and database, sequenceserver and command line BLAST+ leads to different results. Therefore I want to see the BLAST commands executed by sequenceserver (debug). How should I do?

**Comment by yeban** [comment]
With the -D flag. Interested to know what you find.

**Comment by billzt** [comment]
Wow, I know. In sequenceserver, BLASTN is executed by `-task blastn`. While in my own command line, I use the default blastn. This lead to the difference

**Comment by yeban** [comment]
Parameters passed to blast commands, will be shown on the results page in the next release. In the meantime I will be sure to put it somewhere on the website.

**Comment by billzt** [comment]
Thank you. I eagerly hope the new version be released as soon as possible. Nowadays version 1.0.4~1.0.8 hardly involve any commits

**Comment by yeban** [comment]
Yeah, job has been keeping my quite busy. In the little spare time I have had, the preprint, website / documentation updates, etc. were more important. We have a student working on SequenceServer over the summer as part of Google Summer of Code so we can hopefully look forward to what's next soon.
