### ISSUE TITLE
undefined method decode_www_form_component uri module

### ISSUE THREAD

**Issue by jorvis** [wurmlab/sequenceserver#268]
When I first ran sequenceserver the UI came up nicely and things worked until I actually do a blast, then I get the following:

http://imgur.com/0rZZ4kV

In the background there you can see the error.  I'm using Ruby 1.9.1 and there is no error on the terminal running the 'sequenceserver' process.

**Comment by yeban** [comment]
Could you run with `-D` flag (development mode) and see if there is a detailed error message in the terminal? I doubt it though. Looks like the error is raised even before the request reaches the controller. In WEBrick perhaps (the server).

Is is possible for you to use a different Ruby version? Anything >= 1.8.7 but not 1.9.1.

**Comment by jorvis** [comment]
This is what appears when I run it under development mode.  Working now on changing ruby versions.

```
[2016-05-11 11:19:30] ERROR NoMethodError: undefined method `decode_www_form_component' for URI:Module
        /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/utils.rb:51:in `unescape'
        /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/utils.rb:120:in `block (2 levels) in parse_nested_query'
        /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/utils.rb:120:in `map'
        /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/utils.rb:120:in `block in parse_nested_query'
        /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/utils.rb:119:in `each'
        /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/utils.rb:119:in `parse_nested_query'
        /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/request.rb:371:in `parse_query'
        /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/request.rb:215:in `POST'
        /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/request.rb:230:in `params'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:902:in `call!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
        /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
        /var/lib/gems/1.9.1/gems/sequenceserver-1.0.8/lib/sequenceserver.rb:92:in `call'
        /var/lib/gems/1.9.1/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
        /usr/lib/ruby/1.9.1/webrick/httpserver.rb:111:in `service'
        /usr/lib/ruby/1.9.1/webrick/httpserver.rb:70:in `run'
        /usr/lib/ruby/1.9.1/webrick/server.rb:183:in `block in start_thread'
```

**Comment by jorvis** [comment]
I installed Ruby 1.8.7, removed all other versions, and re-installed sequenceserver and it works now.  I'll leave it up to you if you want to close this or leave it open to investigate issues with other ruby versions.

**Comment by yeban** [comment]
Thanks. The error is raised in the libraries we depend on so it will take me some time to figure out and get it sorted.

**Comment by yeban** [comment]
One-off issue. Has been reported on other projects as well with no clear solution. Ruby 1.9.1 was known to be a little buggy, or maybe this bug crept in when packaging Ruby for apt, yum, etc.
