### ISSUE TITLE
Previous results page is not loaded if the result page url points to a specific hit

### ISSUE THREAD

**Issue by uludag** [wurmlab/sequenceserver#277]
Previous results page is not loaded  if the result page url points to a specific hit, as in the following example:

    http://localhost:4567/1b57d1a7-2cad-41c9-b48e-9316275e66e5#Query_1_hit_2

If I remove the hit specific extension (#Query_1_hit_2) result page is loaded and the link for the specific hit works when selected from the graphical overview section.

**Comment by yeban** [comment]
Want to take a shot at fixing that?

**Comment by uludag** [comment]
It looks this problem is fixed if I use location.pathname instead of location.href in fetch_results function in javascript file public/js/report.js

    fetch_results: function () {
        $.getJSON(location.pathname + '.json')

**Comment by yeban** [comment]
Right, that should work. You want to send a PR?
