### ISSUE TITLE
Indicate origin of hit when multiple dbs used

### ISSUE THREAD

**Issue by Shellfishgene** [wurmlab/sequenceserver#279]
Hi,

so BLAST and SequenceServer allow searching multiple databases in one go. However if the sequence names are are similar it seems there is no indication of which hit came from which database. Does BLAST not provide this info or is it just missing from the results in SequenceServer?

**Comment by yeban** [comment]
BLAST does not provide this info. But we have a hack in place to obtain and display this info. Please see [adding links to search hits](http://www.sequenceserver.com/doc/#plugin) section of our documentation and then follow [this mailing list thread](https://groups.google.com/d/msg/sequenceserver/RUOePKmK50g/t0FcGolIAQAJ).
