### ISSUE TITLE
Improved Display of a Long List of Database

### ISSUE THREAD

**Issue by nathanhaigh** [wurmlab/sequenceserver#307]
I'd like to use SequenceServer with a pretty long list of databases. Currently, this takes up a lot of vertical space in the DB selection area. Would it be possible to implement a hierarchy (possibly based on directory structure of the database files) and have it collapsable/expandable? This would be very much in the same vain as lepbase (http://blast.lepbase.org/).

Do you have any thoughts on how this might be implemented in a general way? Alternatively, I could try to port a similar set of changes lepbase have done for the 1.0.x branch onto master. How difficult might this be?

**Comment by yeban** [comment]
I am sorry I couldn't revert sooner. I wasn't well.

My take on this is summed here - https://github.com/wurmlab/sequenceserver/issues/29#issuecomment-143417041. Code is here - https://github.com/yeban/sequenceserver/blob/z/last_from_alekhya/public/js/search.js#L457. It should be relatively simple to apply this code onto master and then to polish it to completion from there.

**Comment by Bjoernsen** [comment]
Are there any news?

**Comment by yeban** [comment]
Sorry, no.

**Comment by yangnaisu** [comment]
lepbase (http://blast.lepbase.org/) seems to be using the jstree plugin, but I don't know how to add it to sequenceserver.

**Comment by jd3234** [comment]
My lab is also very interested in a way to better organize long lists of databases. Are there any activities planned to get that function included? 
PS: Thanks for a great tool!

**Comment by yannickwurm** [comment]
Hello all, 
Thanks for the comments; I agree that it would be great to have this built-in. 
 - the lepbase code is public; so it should be possible for someone to insert that into a sequenceserver (I guess this would be on the stable release, not the 2.0 beta we have in master).
 - I don't think that it would be much additional effort to port it to 2.0. Stress-testing it (and creating relevant unit & integration tests) would need to be done though (e.g. to catch mistakes in how the hierarchy information is provided), as well as creating a threshold for switching from list view to hierarchical view. 

Unfortunately, our BBSRC BBR proposal to integrate the hierarchical (among other improvements) was rejected and resubmission is not allowed. We have another proposal currently under review which - if successful would enable us to implement the feature. Until that funding or another source of cash appears, I am unable to provide an ETA for this...

Kind regards,
Yannick
