### ISSUE TITLE
don't ask questions: --make-blast-db

### ISSUE THREAD

**Issue by audy** [wurmlab/sequenceserver#308]
I'd like to setup a cron job to rebuild my blast databases. Currently, the `--make-blast-db` asks a bunch of questions that I'm okay with just accepting the default answers to. It'd be helpful if there was an additional flag to just accept the defaults for these questions.

I know I can just pipe a bunch of `\n` into the `--make-blast-db` command but thought this would be useful to others.

~~Would you accept a PR to add this feature?~~ Okay it turns out that it's much easier to just pipe newlines 😸 . I'll leave this open in case you think it's a useful feature.

**Comment by vivekiitkgp** [comment]
Thanks @audy. Your post also makes a valuable documentation for those who might need similar functionality later.

On similar note, I think that having a flag, say `--quiet`, might be useful for such circumstances.

**Comment by yeban** [comment]
I don't mind a `-y` option, like `apt-get` has (or maybe it was `aptitude`). A `--quiet` to silence `-m`'s output (if that's what you mean @vivekiitkgp) won't be meaningful though.

If this feature is important, it will come up again. And right now I don't have the resources to dedicated to this. Thus I am closing the issue.

I will very much appreciate documentation related PRs. This info can go under http://www.sequenceserver.com/doc/#database as an alternative to @ar0ch's script.
