### ISSUE TITLE
fail to use sequenceserver (master) with apache httpd server

### ISSUE THREAD

**Issue by billzt** [wurmlab/sequenceserver#314]
I download the 1.0.8 version (put in `/opt/wwwblast/sequenceserver/`) and the master version (put in `/opt/wwwblast/sequenceserver-test/`), intergrated with apache httpd server as:
```
<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /var/www/html
    PassengerLogLevel 0
    TimeOut 600

    <Directory /var/www/html >
        Options -MultiViews
        Require all granted
    </Directory>

    Alias /sequenceserver /opt/wwwblast/sequenceserver/public
    <Location /sequenceserver>
        PassengerBaseURI /sequenceserver
        PassengerAppRoot /opt/wwwblast/sequenceserver
    </Location>

    <Directory /opt/wwwblast/sequenceserver/public>
        Options -MultiViews
        Require all granted
    </Directory>

    Alias /sequenceserver-test /opt/wwwblast/sequenceserver-test/public
    <Location /sequenceserver-test>
        PassengerBaseURI /sequenceserver-test
        PassengerAppRoot /opt/wwwblast/sequenceserver-test
    </Location>

    <Directory /opt/wwwblast/sequenceserver-test/public>
        Options -MultiViews
        Require all granted
    </Directory>
</VirtualHost>
```

when I visit `http://localhost/sequenceserver/` (the 1.0.8 version), it is OK. 
However when I visit `http://localhost/sequenceserver-test/` (the master version), it shows only header and footer, no main window.

![qq 20161010131643](https://cloud.githubusercontent.com/assets/1146090/19227431/cc3f9240-8eeb-11e6-834c-3829e3c53a9f.png)

When I use `bundle exec bin/sequenceserver -D` to debug the master version and visit `http://localhost:4567`, it is also OK. Is the master version can't be intergrated with apache?

**Comment by yeban** [comment]
It's just that without -D SequenceServer loads minified JS and CSS and minified assets on master is roughly a month behind. You can build JS and CSS yourself by running `rake build`.
