### ISSUE TITLE
use kablammo visualization

### ISSUE THREAD

**Issue by MichelMoser** [wurmlab/sequenceserver#316]
Dear sequenceserver developper, 

I saw that you are implementing Kablammo into sequenceserver to visualize blast results. Is there a way to already use that feature? 
I just fetched the most recent commit from sequenceserver but were not able to get the kablammo features to turn on. 
Could you tell me how i could use and test the kablammo feature (maybe also the other visualization features like the circos graph)? Maybe in -devel mode? 

Thank you, 
Michel

**Comment by yeban** [comment]
Both are in master branch, integrated directly into the reports page. Just BLAST (and send feedback!).

**Comment by MichelMoser** [comment]
Hmm, i installed it, blasted sequences but only get regular reports page. 
Do i need some special formatting of the blast db? 
Or installation of some js modules or other ruby gems?

**Comment by yeban** [comment]
Could it be that you are loading the older version by mistake? The version in master branch reads `1.1.0-alpha` in the header of the search form:

<img width="1179" alt="screen shot 2016-11-03 at 7 43 15 pm" src="https://cloud.githubusercontent.com/assets/90373/19969226/d38f77de-a1fd-11e6-982e-7fba2376ae15.png">

Report page opens in a new tab and starts as:

<img width="1020" alt="screen shot 2016-11-03 at 7 44 03 pm" src="https://cloud.githubusercontent.com/assets/90373/19969266/01a7d7a6-a1fe-11e6-98b0-ab2d2293345a.png">

The commit I am talking about is fef144220a62be44eb6d03dfc396fb590a52314e. The following commands should ensure we are seeing the same thing:

```
git clone https://github.com/wurmlab/sequenceserver
gem install bundler
cd sequenceserver
bundle --without development
bundle exec bin/sequenceserver
```

**Comment by MichelMoser** [comment]
yes, sorry was still using latest stable version as default. 
Works now. Thank you!
