### ISSUE TITLE
Is it possible to password protect the access to SequenceServer ?

### ISSUE THREAD

**Issue by ademcan** [wurmlab/sequenceserver#318]
Thank you very much for this tool. I am trying to install and instance of sequenceServer for our collaborators and I would like to password protect its access. Is there an easy way to do that? Of course, one can play a bit with the Apache configuration, but I would like to avoid that.
Thank you.

**Comment by ademcan** [comment]
I just thought of something in the meantime :)
It would be really amazing to have different "status" for different users. This will avoid us to install a specific sequenceServer instance for each project.
Let's say we are working with two collaborators and both want the data to stay private. They could both connect to the same sequenceServer instance (myserver.com/sequenceserver), but they can only Blast against their dedicated Blast db and not the other.
I think this could be a nice feature.

my 2 cents.

**Comment by yeban** [comment]
If you are using SequenceServer with Apache or Nginx then you can easily set up a simple password protection for the URL using HTTP basic auth. Digital ocean has a very good guide for doing so:

[Apache](https://www.digitalocean.com/community/tutorials/how-to-set-up-password-authentication-with-apache-on-ubuntu-14-04)
[Nginx](https://www.digitalocean.com/community/tutorials/how-to-set-up-password-authentication-with-nginx-on-ubuntu-14-04)

**Comment by yeban** [comment]
To have different status for different users, we will need to have the notion of users built in the software first, which I am not sure is within the scope of the project.

**Comment by yeban** [comment]
added a section on password protection to the website - closing this issue
