### ISSUE TITLE
Automatically detect new databases.

### ISSUE THREAD

**Issue by yeban** [wurmlab/sequenceserver#325]
@ar0ch's [gist](https://gist.github.com/ar0ch/2efb5d86ed3b7165443326cec52f2637) (see #257) can be used for now. But would be cool to have the feature built-in.

**Comment by yannickwurm** [comment]
I think we should only detect dbs at startup. Anyone with the ability to add dbs has the ability to restart. Doing things dynamically during runtime creates unnecessary risks and complications.
