### ISSUE TITLE
SequenceServer v1.1.0-alpha does not display on older browsers (eg Chrome r42)

### ISSUE THREAD

**Issue by sujaikumar** [wurmlab/sequenceserver#333]
We're trying SequenceServer v1.1.0-alpha at blast.tardigrades.org and noticed that it does not work on older browsers (eg Safari v9 on mac, and Chrome r42 on Windows). Safari 10 and Chrome r43 onwards work fine.

I realise it is an alpha release but just thought I'd point it out.

**Comment by yeban** [comment]
Thanks.

**Comment by yeban** [comment]
Safari 9 and Chrome 42 have a relatively small userbase compared to latest versions of both - https://caniuse.com/usage-table. Further, given the difficulty in reproducing and addressing issues concerning older browsers locally, I am tempted to let this slide. I think the right approach is to have Travis run the Capybara tests on multiple browsers using SauceLab or so, and fixing the failing tests one by one.

**Comment by yeban** [comment]
I am going to close it as Chrome r42 and Safari 9 should no longer be relevant.
