### ISSUE TITLE
refresh when job is done

### ISSUE THREAD

**Issue by jcsanchez2** [wurmlab/sequenceserver#334]
Using v1.1.0, when launching a job the window wont refresh automatically and you need to click the browser refresh button to actually see the results

**Comment by yeban** [comment]
Can you check and let us know if this is related to #333?

**Comment by jcsanchez2** [comment]
Hi,
I checked and no, it wasnt related, i was trying in firefox r54. And  just tried with a fresh clone version and it works fine now in firefox but also tried chrome r59 to check and in chrome doesnt even show the fasta box to paste the sequence. I am using defaults settings for chrome

Thanks
jc

**Comment by yeban** [comment]
This was fixed recently

**Comment by jcsanchez2** [comment]
Thank you!
