### ISSUE TITLE
minor website bugs

### ISSUE THREAD

**Issue by realsobek** [wurmlab/sequenceserver#338]
I found some minor bugs on SequenceServer's website.
Because I could not find a repo for the website I file the bug report here.

* http://www.sequenceserver.com
The navigation bar overlaps to top part of the content.
You have to delete the navigation bar (f.e. using HTML developer tools; in Mozilla Firefox: Ctrl+Shift+C) in order to see the content below it.
In the HTML-code this is the starting line of the navigation bar:
````
<nav class="navbar navbar-fixed-top" role="navigation">
````

All the following bugs are spelling mistakes.
After the website's URL the first line displays the current spelling. After the "--" separator I propose a fixed version.

* http://www.sequenceserver.com/doc/#basics
preecendence
--
precendence

* http://www.sequenceserver.com/doc/#database
````
The BLAST search algorithms don't directly understand FASTA files.
--
The BLAST search algorithms doesn't understand FASTA files.
````

````
BLAST includes the makeblastdb tool that is used to converts FASTA files
--
BLAST includes the makeblastdb tool that is used to convert FASTA files
````

* http://www.sequenceserver.com/doc/#ncbi-databases
datbases
--
databases

* http://www.sequenceserver.com/doc/#plugin
Sequenceserver provides ...
--
SequenceServer provides ...

* http://www.sequenceserver.com/doc/#sharing
Administrator previlege
--
Administrator privilege

* http://www.sequenceserver.com/doc/#macosx
Autostart on Mac OSX
--
Autostart on Mac OS X

* http://www.sequenceserver.com/doc/#issues
Ths appears
--
This appears

* http://www.sequenceserver.com/doc/#blast
commerical
--
commercial

* http://www.sequenceserver.com
````
Useability
--
Usability
````

````
preferrably
--
preferably
````

````
Envrionmental
--
Environmental
````

````
Comparitive
--
Comparative
````

````
Tuebigen
--
Tuebingen
better: Tübingen
HTML-code of ü: &uuml;
````

````
(eg:
--
(e.g.:
````

**Comment by yannickwurm** [comment]
Dear @realsobek, 
thank you so much for highlighting these issues. We will rapidly address them. 
FWIW, I believe the website is served directly from the `gh-pages` branch of this repo. 
Kind regards,

Yannick


---------------------------------------------------------------------------------
https://wurmlab.github.io    y.wurm@qmul.ac.uk    Ants, Bees, Genomes & Evolution
skype:yannickwurm +44 207 882 3049
5.21 Fogg, Organismal Biology, Queen Mary U London, Mile End Rd, E14NS London, UK
>
> Fire ant social supergene Gp-9s http://bit.ly/social_chromosome_odorant_proteins
> Social chromosome diversity:           http://bit.ly/social_chromosome_diversity
> GeneValidator: Visualise gene prediction quality        http://bit.ly/gvalidator
>
> Bioinformatics Msc programme:            http://bit.ly/london-bioinformatics-msc
> Ecological & Evolutionary Genomics MSc program:  http://bit.ly/evol-genomics-msc

**Comment by realsobek** [comment]
In that case let me create a pull request.

**Comment by realsobek** [comment]
FYI: I noticed that Guy Leonard's picture and website on SequenceServers's website is broken. I sent Guy an email. Maybe it will be a separate PR.

**Comment by realsobek** [comment]
Guy said I can use his GitHub website because the other website is being re-implemented.
From my point of view we can take the discussion to the pull request.

**Comment by yeban** [comment]
@realsobek wrote:
> The navigation bar overlaps to top part of the content.
You have to delete the navigation bar (f.e. using HTML developer tools; in Mozilla Firefox: Ctrl+Shift+C) in order to see the content below it.

Can you post a screenshot?

**Comment by realsobek** [comment]
This setting allows reproduction:
firefox -- about:preferences#content -- Fonts & Colors -- [Advanced...] -- [] Allow pages to choose their own fonts, instead of my selections above

This expands the navbar from one to two rows.
Because the content does not get pushed further down automatically the top navbar with two rows overlaps the content.

A cropped screenshot is attached:
![issue338](https://user-images.githubusercontent.com/18424198/30703404-e53ce148-9eef-11e7-94d0-45638b2a4ee8.jpg)
