### ISSUE TITLE
ubuntu bug large db

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/sequenceserver#341]
`sequenceserver -d dir_with_large_db `
led to a strange error during startup using BLAST 3.3.31 today on ubuntu in our room Fogg 3.15. 

This error occured: 
 - with a freshly makeblastdb'ed uniref50 (fasta to blastdb on the same 3.3.31 machine)
- with a uniref50 on which makeblastdb' was run on apocrita (prob using blast 2.2.26) ~/db/other/uniref50/2017-07 
- but not with freshly formatted swissprot. 

Directory included no other dbs

I think its a pb with blast (during the command that searches for dbs with custom outfmt), rather than a pb with seqserv.

**Comment by yannickwurm** [comment]
deets:

> 
> Yannick@n56-215 /V/c/tmp> sequenceserver -d  /Volumes/apocrita/db/other/uniref50/2017-07
> Error obtaining BLAST databases.
> Tried: blastdbcmd -recursive -list /Volumes/apocrita/db/other/uniref50/2017-07 -list_outfmt "%f	%t	%p	%n	%l	%d"
> Error:
> BLAST Database error: CSeqDBAtlas::MapMmap: While mapping file [/Volumes/apocrita/db/other/uniref50/2017-07/uniref50.fasta.00.nin] with 0 bytes allocated, caught exception:
> NCBI C++ Exception:
>     T0 "/Users/coremake/release_build/build/PrepareRelease_IntelMAC_JSID_01_10336_130.14.22.10_9008__PrepareRelease_IntelMAC_1414443170/c++/compilers/unix/../../src/objtools/blast/seqdb_reader/seqdbatlas.cpp", line 152: Error: BLASTDB::ncbi::SeqDB_ThrowException() - Validation failed: [end <= file_size] at /Users/coremake/release_build/build/PrepareRelease_IntelMAC_JSID_01_10336_130.14.22.10_9008__PrepareRelease_IntelMAC_1414443170/c++/compilers/unix/../../src/objtools/blast/seqdb_reader/seqdbatlas.cpp:506
> 
> Please could you report this to 'https://groups.google.com/forum/#!forum/sequenceserver'?
> Yannick@n56-215 /V/c/tmp> blastdbcmd -recursive -list /Volumes/apocrita/db/other/uniref50/2017-07 -list_outfmt "%f%t%p%n%l%d"                                         1
> /Volumes/apocrita/db/other/uniref50/2017-07/uniref50.fastauniref50Protein235319807236829787Jul 23, 2017  7:00 PM
> /Volumes/apocrita/db/other/uniref50/2017-07/uniref50.fasta.00uniref50Protein2689141997310752Jul 23, 2017  7:00 PM
> BLAST Database error: CSeqDBAtlas::MapMmap: While mapping file [/Volumes/apocrita/db/other/uniref50/2017-07/uniref50.fasta.00.nin] with 0 bytes allocated, caught exception:
> NCBI C++ Exception:
>     T0 "/private/tmp/blast-20170511-49816-1rw4ib1/ncbi-blast-2.6.0+-src/c++/src/objtools/blast/seqdb_reader/seqdbatlas.cpp", line 149: Error: BLASTDB::ncbi::SeqDB_ThrowException() - Validation failed: [end <= file_size] at /private/tmp/blast-20170511-49816-1rw4ib1/ncbi-blast-2.6.0+-src/c++/src/objtools/blast/seqdb_reader/seqdbatlas.cpp:503

**Comment by yeban** [comment]
Looks like a system error, potentially at file system level. Not sure what can be done. Do you have any idea?

**Comment by yeban** [comment]
Shall we close this?

**Comment by yannickwurm** [comment]
it didn't occur the following 2 years, and nobody else has reported this so indeed may have been a strange interaction of things
