### ISSUE TITLE
Forbidden AA not filtered and error not thrown

### ISSUE THREAD

**Issue by bordin89** [wurmlab/sequenceserver#349]
There is an issue with the FASTA format checker in SequenceServer. Special characters are filtered out, but letters that are not AAs (such as B,O,J,U,Z) pass through and are still present in the alignment.
Is there a way to fix this? Which part of the code performs the check? 

Thanks.

**Comment by yeban** [comment]
Hi. Filtering chars and determining sequence type is done by [`guessSequenceType` function in search.js](https://github.com/wurmlab/sequenceserver/blob/master/public/js/search.js#L311).

**Comment by yeban** [comment]
I am closing this because it's not clear what can be done. Also, SequenceServer does not change the user-submitted sequence in any way. There is a temporary cleanup, only to reduce noise in guessing sequence type. Rest is handled by BLAST itself.
