### ISSUE TITLE
search advanced parameters

### ISSUE THREAD

**Issue by yeban** [wurmlab/sequenceserver#35]
_Incrementally_ filter out (like bubble to top, or maybe hide other options) advanced parameters, as the user types it out.

We might need to slightly change how advanced parameters are entered, maybe JSON instead of CLI format. Not sure if we should filter out only on keywords (evalue, num_alignments, entrez_query, etc), or do a (kind of) full text search.

Will probably do this after 1.0. Suggestions, thoughts, and +/- 1 welcome :).

**Comment by malcook** [comment]
+1 - especially if you find some way to guide the user through the creation of a legal command line, that would be best of both worlds in that the user would learn skills transferable to command line usage.

**Comment by yeban** [comment]
The effort required to implement this is too much, for too little return. Features like #48 and bug fixes should be the higher priority.
