### ISSUE TITLE
FASTA check performed only on the first header, not on all the files.

### ISSUE THREAD

**Issue by bordin89** [wurmlab/sequenceserver#350]
Hi,

I noticed that if you try to upload or copy paste more than one sequence and you remove any ">" (not the first), Sequenceserver treats the following header and sequence as part of the previous sequence. 

Is there a quick way to fix this?

Nicola

**Comment by yannickwurm** [comment]
Hi Nicola,  was this a false alert or still something we need to look into? 
Thanks
yannick

**Comment by bordin89** [comment]
Hi Yannick, 

It's still something to look into, but it's a strong limitation of BLAST itself (the same problem happens also on the NCBI BLAST website. If you concatenate by mistake two sequences by removing a ">", the programs sees it as a single protein and will treat any character as an AA and will remove any non-character. For the NCBI BLAST is not a big deal (for them) since it's meant only for single sequence searches, but since SequenceServer allows multiFASTAs this could be a major issue.

**Comment by yannickwurm** [comment]
You mean like the following example?

>sequence1
AYGTKALGTHBLH
sequence2
AYGTKGHLLLLLLALGTHBLH


I'm unsure how we could easily detect that. If the identifier is very long, then we could put an alert e.g. if there are many non-IUPAC characters?  (but what is the threshold?)

**Comment by bordin89** [comment]
![screenshot from 2018-03-15 11-55-02](https://user-images.githubusercontent.com/8873935/37458976-f5e79868-2846-11e8-86cd-093d8ea3a9e4.png)

Something like this. 
I don't think it's possible to detect. This is more of a BLAST algorithm issue than a SequenceServer issue. BLAST from the command-line allows multiFASTA and the behavior is the same as in SS.

**Comment by yannickwurm** [comment]
Well - similarly to our detecting whether nucleotide or aminoacid, we could do a check to see if there are e.g. more than 1% of nonIUPAC characters and if that is the case display some sort of alert.
