### ISSUE TITLE
perc_identity blast parameter causes error

### ISSUE THREAD

**Issue by tomas-pluskal** [wurmlab/sequenceserver#359]
Running SequenceServer 1.1.0.beta5 and entering ```-perc_identity 95``` into the Advanced Parameters field resulted in this error: **undefined local variable or method `this' for #**

````
/lab/solexa_weng/tmp/TP/sequenceserver-1.1.0.beta5/lib/sequenceserver/blast/job.rb:39:in `raise!'
/lab/solexa_weng/tmp/TP/sequenceserver-1.1.0.beta5/lib/sequenceserver/blast/report.rb:46:in `generate'
/lab/solexa_weng/tmp/TP/sequenceserver-1.1.0.beta5/lib/sequenceserver/report.rb:27:in `initialize'
/lab/solexa_weng/tmp/TP/sequenceserver-1.1.0.beta5/lib/sequenceserver/blast/report.rb:25:in `initialize'
/lab/solexa_weng/tmp/TP/sequenceserver-1.1.0.beta5/lib/sequenceserver/report.rb:15:in `new'
/lab/solexa_weng/tmp/TP/sequenceserver-1.1.0.beta5/lib/sequenceserver/report.rb:15:in `generate'
/lab/solexa_weng/tmp/TP/sequenceserver-1.1.0.beta5/lib/sequenceserver/routes.rb:87:in `block in <class:Routes>'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1633:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1633:in `block in compile!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1011:in `route_eval'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1039:in `block in process_route'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `catch'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `process_route'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:990:in `block in route!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `each'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `route!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1096:in `block in dispatch!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1093:in `dispatch!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `block in call!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `call!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:913:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/rack-2.0.5/lib/rack/deflater.rb:34:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:194:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1957:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `block in call'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1728:in `synchronize'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `call'
/lab/solexa_weng/tmp/TP/sequenceserver-1.1.0.beta5/lib/sequenceserver.rb:194:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/rack-2.0.5/lib/rack/handler/webrick.rb:86:in `service'
/usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
````

**Comment by yeban** [comment]
Hello Tomáš. Thanks for testing the beta! This is a small typo in the code. ‘this’ on line 39 in lib/sequenceserver/blast/job.rb should be ‘self’.

I am away till May 13th. I will fix it when I am back, or a pull-request will be nice.

Sent from my iPhone

On 30 Apr 2018, at 21:24, Tomáš Pluskal <notifications@github.com<mailto:notifications@github.com>> wrote:


Running SequenceServer 1.1.0.beta5 and entering -perc_identity 95 into the Advanced Parameters field resulted in this error: undefined local variable or method `this' for #

/lab/solexa_weng/tmp/TP/sequenceserver-1.1.0.beta5/lib/sequenceserver/blast/job.rb:39:in `raise!'
/lab/solexa_weng/tmp/TP/sequenceserver-1.1.0.beta5/lib/sequenceserver/blast/report.rb:46:in `generate'
/lab/solexa_weng/tmp/TP/sequenceserver-1.1.0.beta5/lib/sequenceserver/report.rb:27:in `initialize'
/lab/solexa_weng/tmp/TP/sequenceserver-1.1.0.beta5/lib/sequenceserver/blast/report.rb:25:in `initialize'
/lab/solexa_weng/tmp/TP/sequenceserver-1.1.0.beta5/lib/sequenceserver/report.rb:15:in `new'
/lab/solexa_weng/tmp/TP/sequenceserver-1.1.0.beta5/lib/sequenceserver/report.rb:15:in `generate'
/lab/solexa_weng/tmp/TP/sequenceserver-1.1.0.beta5/lib/sequenceserver/routes.rb:87:in `block in <class:Routes>'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1633:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1633:in `block in compile!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1011:in `route_eval'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1039:in `block in process_route'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `catch'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `process_route'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:990:in `block in route!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `each'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `route!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1096:in `block in dispatch!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1093:in `dispatch!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `block in call!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `call!'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:913:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/rack-2.0.5/lib/rack/deflater.rb:34:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:194:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1957:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `block in call'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1728:in `synchronize'
/home/pluskal/.gem/ruby/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `call'
/lab/solexa_weng/tmp/TP/sequenceserver-1.1.0.beta5/lib/sequenceserver.rb:194:in `call'
/home/pluskal/.gem/ruby/2.3.0/gems/rack-2.0.5/lib/rack/handler/webrick.rb:86:in `service'
/usr/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/usr/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/usr/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
