### ISSUE TITLE
Enter taxid requires input despite being optional

### ISSUE THREAD

**Issue by tomas-pluskal** [wurmlab/sequenceserver#361]
Hi,

In the development version of sequenceserver, when creating the blast databases the user needs to enter something for taxid - empty string is not accepted:
https://github.com/wurmlab/sequenceserver/blob/master/lib/sequenceserver/database.rb#L216

This complicates scripting of the database creation. Also it's not counterintuitive, because the taxid is marked as optional.

In older versions of sequenceserver it was okay to enter an empty string (just press Enter).

I would recommend to allow empty input again.

Thanks,

Tomas

**Comment by yeban** [comment]
Agreed. I probably introduced the bug in trying to make sure sequenceserver doesn’t crash if input taxid is non-numeric
