### ISSUE TITLE
Results page doesn't seem to refresh upon completion

### ISSUE THREAD

**Issue by dpryan79** [wurmlab/sequenceserver#364]
I'm currently using 1.1.0.beta7 to enable support for downloading fasta results when there are more than 32 hits. One issue that's been reported to me by some of our local sequenceserver users is that the page doesn't actually update with the results once the blast command finishes. Instead, you get this endless spinning circle indicating that it's working and need to occasionally refresh the page. Once the query is actually finished and the page is manually refreshed the results look completely as expected, so there doesn't appear to be an error anywhere.

**Comment by yeban** [comment]
Sorry about that. I will include a fix in the next beta.

**Comment by yannickwurm** [comment]
Thanks v much for the report @dpryan79

**Comment by raivivek** [comment]
It looks like an interesting example for the test suite.
