### ISSUE TITLE
blast admin page

### ISSUE THREAD

**Issue by mictadlo** [wurmlab/sequenceserver#367]
Hi,
Someone [here](https://github.com/fikipollo/blast-docker) wrote a nice Blast admin page which works as well with sequenceserver. Any plans to merge this feature?

Best wishes,

Michal

**Comment by yeban** [comment]
I wasn't aware of it. Thanks for sharing. It is very nice indeed. At the moment there are no plans to integrate it. In fact, I think it's best that admin interface exists as a separate repository and that it be maintained by the community.
