### ISSUE TITLE
Docker hub images have wrong sequenceserver version

### ISSUE THREAD

**Issue by zdk123** [wurmlab/sequenceserver#372]
I am testing out the new beta and I came across the following issue:

Pull in the specified tag from dockerhub:
```
docker run -ti --entrypoint "/bin/bash" -p 4567:4567 -v /mnt/DataDrive1/sequenceserver/:/db wurmlab/sequenceserver:1.1.0.beta10
```
log into the running container, we can see that sequenceserver is not the correct version:
```
root@6a0f6eeb6371:/# sequenceserver --version
1.0.11
```
I can update within the container:
```
root@6a0f6eeb6371:/# gem install --pre sequenceserver
root@6a0f6eeb6371:/# sequenceserver --version
1.1.0.beta11
```

I'm also getting the error message that the packaged blast version (2.2.31) is also incompatible:
`SequenceServer needs NCBI BLAST+ version 2.6.0+`

Downgrading to beta9 has the same issue.

I would love to know if this is isolated to my machine, thanks!

**Comment by yeban** [comment]
This is not isolated to your machine - see e3df71c7. Following that commit, the build rule on docker hub needed changing, which I did now and triggered a new build. Docker image tagged 1.1.0.beta11 and subsequent releases should work fine.

Thanks!
