### ISSUE TITLE
get PreDefinedOpts from config file

### ISSUE THREAD

**Issue by zdk123** [wurmlab/sequenceserver#373]
This is a feature request.

I quite like that predefined options get pre-populated in the "advanced parameters" window. This can guide users towards using parameters that work for most setups without forcing them for special queries.

I see that these are currently hardcoded in the `GetInitialState` [javascript function](https://github.com/wurmlab/sequenceserver/blob/9fffd62b6b4e072f51cd5e89a90e9e123f3903b8/public/js/search.js#L203-L207). 

Would it be feasible to instead define this as a section in the config file?

**Comment by yeban** [comment]
You can override them using the config file - an example below.


```
---
:port: 4567
:host: 0.0.0.0
:num_threads: 8
:bin: "/Users/priyam/.sequenceserver/ncbi-blast-2.6.0+/bin"
:database_dir: "/Users/priyam/wurmlab/sequenceserver/spec/database/sample"
:options:
  blastn: ['-evalue 10 -task megablast']
  blastp: ['-evalue 10']
  blastx: ['-evalue 10']
  tblastn: ['-evalue 10']
  tblastx: ['-evalue 10']
```

**Comment by zdk123** [comment]
confirmed that this works in the latest beta release.
