### ISSUE TITLE
custom links for each Blast hit

### ISSUE THREAD

**Issue by mictadlo** [wurmlab/sequenceserver#374]
Hi,
Currently, each Blast has a FASTA, Alignment, and NCBI link
![Image of Yaktocat](https://user-images.githubusercontent.com/90373/42143112-6076eb16-7dab-11e8-85c1-8ceb5a5ed690.png)

How is it possible to add a JBrowse link?

Thank you in advance.

Michal

**Comment by yeban** [comment]
You can add custom links in the same way as for the old stable release: http://www.sequenceserver.com/doc/#plugin. Additionally, there are a few threads on Google Group where linking to JBrowse is discussed in more detail.

One new addition is that you can now call [`coordinates`](https://github.com/wurmlab/sequenceserver/blob/master/lib/sequenceserver/blast/hit.rb#L44) method inside of a link generator to get coordinates of the matching region on both query and the hit.
