### ISSUE TITLE
Disable download of "Fasta of all hits"

### ISSUE THREAD

**Issue by andreaminio** [wurmlab/sequenceserver#381]
Hi everyone,

I was trying to remove the download of the entire FASTA sequence of targets of a blast search as the entire sequence is reported and not only the region of interest. I don't know if this behaviour will change at some point, but the actual behaviour is something I don't desire.
While it was easy to remove the link from each entry (editing links.rb file), I was trying to edit the side bar where "**Download FASTA, XML, TSV**" with _FASTA of all hits_ and _FASTA of selected hit(s)_ are as I don't want to allow bulk download of the entire chromosome sequences, but I found no way to remove/disable or making not working this links. In the best case, removing the list elements in _views/result.erb_ file removes the link but the "searching" pop-up window never leave from in front of the results, editing the content of the ruby search in the link obviously breaks the code delivering errors. 
As I'd like to keep the tabular and xml report download active, how can I disable just the FASTA download?

Thanks in advance 

Andrea

**Comment by yeban** [comment]
Happy to help :)
