### ISSUE TITLE
sub uri with beta version - working?

### ISSUE THREAD

**Issue by guyleonard** [wurmlab/sequenceserver#388]
Hey All! 

It's been a while! Hope you're all well :) 

I was trying to get the latest beta running with multiple versions on sub uris. But maybe this is just not possible at all yet. But it seems so close! For example:

My set-up:

Apache2.4.18, Ruby 2.3.1p112, Ubuntu 16.04

I have a symlink of the ruby installation to my /usr/share directory.

`/usr/share/sequenceserver_beta -> /var/lib/gems/2.3.0/gems/sequenceserver-1.1.0.beta12/`

Then in /etc I have a folder for each server I want to run , e.g. "blast_testing" and the contents of this directory is symlinked to the the contents of /usr/share/sequenceserver_beta. Except for the config.ru and config.yml files which are not symlinks but actual files. They look like this:

config.ru
```
require 'sequenceserver'
SequenceServer::DOTDIR="/var/www/sequenceserver/testing2"
SequenceServer.init :config_file => ("/etc/blast_testing2/config.yml")
run SequenceServer

```
config.yml
```
database_dir: /blast_databases/testing
port: 5127
num_threads: 1
```

The server side I have:

A folder called /var/www/sequenceserver/testing2 - as pointed to from the config.ru file.

Along with 000-default.conf that looks like below (relevant sections only shown) - with the new style of phusion passenger set up.

```
... 
        ## Ruby version for Passenger
        PassengerRuby /usr/bin/ruby
        # Allow writing to www-data owned dirs
        # instead of nobody/nogroup in sandbox mode 
        PassengerDefaultUser www-data
        PassengerDefaultGroup www-data

        Alias /testing2 /etc/blast_testing2/public
 
        <Location /testing2>
                PassengerBaseURI /testing2
                PassengerAppRoot /etc/blast_testing2/
        </Location>
 
        <Directory /etc/blast_testing2/public>
                Allow from all
                Options -MultiViews +Indexes +FollowSymLinks
                Require all granted
                PassengerFriendlyErrorPages on
        </Directory>
... 

```
That all works nicely (and had worked nicely for pre-beta versions too).

However, when I go to http://my-url.local/testing2 I see the user interface for sequenceserver and everything starts up okay. But when I add a sequence and select a DB and hit blastX my browser refers me to http://my-url.local/9ab48ecc-4c23-469c-b50a-f5e55be47c16 rather than http://my-url.local/**testing2**/9ab48ecc-4c23-469c-b50a-f5e55be47c16 - it does not keep the SUB URI part of the domain.

So, it is almost there, and indeed, if I go to what should be the correct URL, I get the results page and everything has run correctly (or rather runs for the current viewing). 

Have I totally missed something in this set up, or is sub uri just not quite ready yet? No worries if not I can wait or figure something out.

Best,

Guy

**Comment by yeban** [comment]
I thought I had it fixed in the 11th beta release but looks like I had missed something. Just pushed a small change (see the commit linked above). Please could you test it by running sequenceserver from a git clone?

**Comment by guyleonard** [comment]
Yup that works a treat! Thanks for the fast response!

Guy

**Comment by yeban** [comment]
Thanks for raising the issue.

---
On a related note, in a reverse proxy setup it may be important for the forwarding server to set `X-Forwarded-Host` header. On Nginx, this can be done by adding the following to a `location` block:

    proxy_set_header   X-Forwarded-Host $host:$server_port;
