### ISSUE TITLE
sometimes forced tblastx

### ISSUE THREAD

**Issue by GRGong** [wurmlab/sequenceserver#393]
Hi, I want to know when sequenceserver choose blastn and when choose tblastx, sometimes I can only use tblastx(only one option), is it a bug?

**Comment by yeban** [comment]
No distinction between blastn and tblastx for nucleotide-nucleotide comparison. blastn is selected by default. You should be able to choose tblastx by clicking the little downward-facing arrow button next to the main one.

Could you provide an example to reproduce the issue you are facing?
