### ISSUE TITLE
Query textbox should be vertically resizable

### ISSUE THREAD

**Issue by yeban** [wurmlab/sequenceserver#401]
I have tried all the standard solutions, I think. Beats me why the query textarea remains unresizable. Dunno if react somehow gets in the way.

**Comment by Iain-S** [comment]
It looks like the notifications div immediately below the text area overlaps it.  Trying to drag the text area corner probably just clicks the notification element instead.

See below for a screenshot of the problem using Developer tools on Opera 72.0.  Notice that the top position of the notifications is -16px.

![sequence server 2020-10-26](https://user-images.githubusercontent.com/25081046/97190270-6d8a0c00-179d-11eb-8b05-191741eefecc.jpg)

I can think of two easy fixes, both of which require changes to public/css/sequenceserver.css:

```
325 .query-container {
326   margin-top: 35px;
327   margin-bottom: 0;
328 }
329 
330 .notifications {
331   position: relative;
332   height: 32px;
333   top: -16px;
334 } 
335 .notification {
336   height: 32px !important;
337 } 
```

1. Delete line 333 so that the two elements don't overlap: ~`top: -16px;`~
2. Add a line below 333 to push the notifications element behind the text area: `z-index: -1;`

I couldn't say which, if either, is better because I'm not sure why the negative position was chosen to begin with.

If we go with option 1, we see that the text area is now draggable, though further testing would need to be done since I did not trigger any notifications:

![sequence server opt 1 2020-10-26](https://user-images.githubusercontent.com/25081046/97191169-81823d80-179e-11eb-8814-8e9686aaaaaf.jpg)

**Comment by yeban** [comment]
Thanks, I am delighted to be receiving detailed and insightful feedback on this issue. The solutions fall short a bit short though:

Option 1

<img width="1170" alt="sol1" src="https://user-images.githubusercontent.com/90373/97204031-7da9e780-17ad-11eb-87d2-2c308355de90.png">

Option 2

<img width="1165" alt="sol2" src="https://user-images.githubusercontent.com/90373/97204037-7f73ab00-17ad-11eb-947a-bdc9040bc513.png">


Type/pasting minimum 10 characters in the textarea, e.g. `ATGCATGCATGC`, will trigger notifications. Negative placement was chosen so that the notification is vertically centered on the bottom border of the textarea:

Normal

<img width="1163" alt="Screenshot 2020-10-26 at 17 09 53" src="https://user-images.githubusercontent.com/90373/97204621-36702680-17ae-11eb-81eb-b810bcc5de01.png">

Also, relative positioning was chosen so that displaying and hiding notification does not cause the database listing below it to move up and down. Do you know of another way to achieve the same effect as `position: relative; top: -16px;`?

**Comment by Iain-S** [comment]
Hello, thanks for the quick response. I don't know any other way to get the same effect as `position: relative; top: -16px;` but there is another solution that may be acceptable:

Option 3: Make the notifications element a little narrower using margins.  That way, it clears the drag marker, which seems to be put in the bottom right corner by all browsers.

```
325 .query-container {
326   margin-top: 35px;
327   margin-bottom: 0;
328 }
329 
330 .notifications {
331   position: relative;
332   height: 32px;
333   top: -16px;
334   margin-right: 35px;
335   margin-left: 35px;
336 }
337 .notification {
338   height: 32px !important;
339 } 
```
That gives us:

![sequence server opt 3 2020-10-27](https://user-images.githubusercontent.com/25081046/97302621-3bd27d00-1851-11eb-97e9-ca75893324b5.png)

As an added bonus, the notification looks a little neater on narrower screens, where the notification currently strays wider than the text area:

**Before**

![sequence server existing 2020-10-27](https://user-images.githubusercontent.com/25081046/97302680-4bea5c80-1851-11eb-9fca-52c844d4616e.jpg)

**After**

![sequence server margin 2020-10-27](https://user-images.githubusercontent.com/25081046/97302696-50167a00-1851-11eb-9b7b-156f5df8e81f.jpg)

Can you think of any disadvantage to this approach?

**Comment by yannickwurm** [comment]
That looks superb to me! (but haven't tested)

**Comment by yeban** [comment]
Oh my god! This is amazing! It works! The problem was on our radar almost a year before we opened this GitHub issue.

Since you asked, a very minor problem is when a user pastes mixed nucleotide and amino acid sequence. The error notification show in this case is slightly wordier and wraps to a second line at 991 px instead of the previous 711 px.

But I am not complaining. Wordiness of the message and padding around the text can be adjusted to give the text more room - I would be happy to take care of that. Furthermore, I like how the notification stays within the bounds of textarea with your approach.

How would you like to proceed? Do you intend to send a pull-request/patch, or do you want me to apply the proposed change myself?

**Comment by Iain-S** [comment]
Hello.  Sorry for the slow response.  I shall submit a PR to your master from my fork now.  I shan't try to adjust the messages or text padding, I'll leave that to you.

On another note, I notice that there are some max-stack-depth-exceeded errors in the console output.  I think there's some mutual recursion between `handleClick` and `componentDidUpdate`.  Is there already an issue for this?  If not, I can open one.

**Comment by yeban** [comment]
> On another note, I notice that there are some max-stack-depth-exceeded errors in the console output. I think there's some mutual recursion between handleClick and componentDidUpdate. Is there already an issue for this? If not, I can open one.

I am aware of it, but do feel free to open one. Generally doesn't impact the user experience, but can sometimes. Only happens if you have one databases or when you use back button go back to search form from results page.

**Comment by yeban** [comment]
> > On another note, I notice that there are some max-stack-depth-exceeded errors in the console output. I think there's some mutual recursion between handleClick and componentDidUpdate. Is there already an issue for this? If not, I can open one.
>
> I am aware of it, but do feel free to open one. Generally doesn't impact the user experience, but can sometimes. Only happens if you have one databases or when you use back button go back to search form from results page.

I have fixed this in master (in case this was still in your todo list).

**Comment by yeban** [comment]
Merged the PR and made the mixed-sequence-type notification less wordy. Thanks again!
