### ISSUE TITLE
Update BLAST version in Docker image

### ISSUE THREAD

**Issue by nathanweeks** [wurmlab/sequenceserver#405]
NCBI BLAST >= 2.8.0 is needed to use NCBI's [BLAST database version 5](https://ftp.ncbi.nlm.nih.gov/blast/db/v5/blastdbv5.pdf) format. Could the SequenceServer Docker image be updated to use a newer BLAST than its current 2.6.0?

It looks like the Debian ncbi-blast+ package will be at version 2.8.1 when Debian Buster is released in July (https://packages.debian.org/testing/science/ncbi-blast+). OTOH, if feasible from a technical/political/license perspective, it may be worthwhile to use the [official NCBI BLAST+ Docker image](https://github.com/ncbi/docker/tree/master/blast) as the base image for SequenceServer, as it should always have the latest BLAST, and presumably be better tested than any distribution-specific BLAST package.

**Comment by yeban** [comment]
Other aspects of SequenceServer will need to be tested as well. The last time I checked, there were problems using BLAST 2.7 and/or 2.8 with SequenceServer. I didn't narrow down the problem, but I believe the required changes should be minor. 

@ivopieniak in our lab is looking into this at the moment.

**Comment by yeban** [comment]
SequenceServer now uses BLAST 2.9 (82668db2b749c02db8272bc8468dd4516b6d531a). The Dockerfile has been updated as well (5beb7fda6458c5160942c9e679ca21a54d0d6422) - precompiled BLAST binaries are automatically downloaded by sequenceserver.

The new image should be built automatically and available for download when we make a new beta release (which I am hoping is next week). In the mean time please feel free to test by building the docker image locally and reporting any issues.
