### ISSUE TITLE
New Dockerfile

### ISSUE THREAD

**Issue by mictadlo** [wurmlab/sequenceserver#412]
Hi all,
Please find below my `Dockerfile`
```
FROM debian:stretch-backports
RUN apt-get update  && apt-get install -y --no-install-recommends \
        build-essential \
        ruby ruby-dev \
        curl wget \
        gnupg \
        git \
        ncbi-blast+ zlib1g-dev 

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - && \
        apt-get update  && apt-get install -y --no-install-recommends \
        nodejs && \
        rm -rf /var/lib/apt/lists/*

RUN gem install bundler && \
    gem install rake && \
    wget -c https://github.com/wurmlab/sequenceserver/archive/1.1.0.beta12.tar.gz  && \
    tar xfvz 1.1.0.beta12.tar.gz && \
    cd sequenceserver-1.1.0.beta12 && \
    npm install && \
    bundle install

VOLUME ["/db"]
EXPOSE 4567
WORKDIR /sequenceserver-1.1.0.beta12
ENTRYPOINT bundle exec bin/sequenceserver -database_dir=/dbs --num_threads=4
```
and this is `docker-compose.yml`

```
sequenceserver:
  build: .
  restart: always
  ports:
    - "4567:4567"
  volumes:
    - ./data/sequenceserver:/db 
```

I started it by `docker-compose up --build` which caused:
```
...
sequenceserver_1  | fatal: Not a git repository (or any of the parent directories): .git
sequenceserver_1  | stty: 'standard input': Inappropriate ioctl for device
sequenceserver_1  | [2019-08-15 02:25:58] INFO  Configuration file not found: /root/.sequenceserver.conf
sequenceserver_sequenceserver_1 exited with code 1
```
What would be the best way to create the configuration file? 

Thank you in advance,

Michal

**Comment by yeban** [comment]
SequenceServer always looks for a configuration file at startup, but it doesn't fail if it doesn't find one.

I can think of two reasons why your setup is failing:
1. Relative path in volumes. If I remember correctly, relative paths don't work with `docker run` command.
2. BLAST version is incompatible. Version 1.1.0-beta12 expects BLAST 2.6.0 I believe. The thing is, it expects the exact version (not >= as one might think).

Best way to install BLAST in the container is to use sequenceserver itself:

https://github.com/wurmlab/sequenceserver/commit/5beb7fda6458c5160942c9e679ca21a54d0d6422

**Comment by mictadlo** [comment]
Hi,
The above Docker file installs 

```
Step 5/9 : RUN blastn -version
 ---> Running in 3c45402820b1
blastn: 2.6.0+
```

I have another `docker-compose.yml` for another project and `./data/:/data` seems to work.

What else could I miss?

Thank you in advance

Michal

**Comment by yeban** [comment]
The only other thing I can think of is this line:

> ENTRYPOINT bundle exec bin/sequenceserver -database_dir=/dbs --num_threads=4

Should be `--database_dir`. I didn't say anything ealier because I thought it was a copy-paste error.

**Comment by yeban** [comment]
Hi @mictadlo. Did you get this working eventually? I was wondering if you had a chance to keep up with the releases and test version 2.0-rc1 with docker?
