### ISSUE TITLE
Optimise docker image

### ISSUE THREAD

**Issue by yeban** [wurmlab/sequenceserver#413]
The docker image for beta is pretty big: ~500 Mb

1. ~~Add `rm -rf /var/lib/apt/lists/*` to RUN directive on line number 8 (run `git log -p Dockerfile` to see how it was done before and how it accidentally got removed).~~
2. ~~Combine RUN directive in line number 21 and 22 into one (`gem install bundler && bundle install --without=development && echo "\n/db\nn" | bundle exec bin/sequenceserver -s` - i.e., yes to download blast, /db for location of database dir, and no for scanning database dir as the database dir would be empty while building the image on docker hub)~~

3. Remove the BLAST tarball downloaded by sequenceserver from /tmp

**Comment by neelkamath** [comment]
I'll try

**Comment by neelkamath** [comment]
Running `docker build -t ss .`, and then `docker run --rm -it ss bash`, and then `ls /tmp` shows no files. Where exactly is the BLAST tarball? If it's not there, perhaps you'd want to remove the README, etc. from the Docker image.

**Comment by yeban** [comment]
Sorry, it seems the tarball is downloaded to `/root/.sequenceserver` in the container.

**Comment by yeban** [comment]
Removing README etc. won't have a major impact. Inside `/root/.sequenceserver/ncbi-blast-2.10.0+/bin/` there are a bunch of binaries that we do not use. Removing them will likely help more. The binaries we use are: `blastp`, `blastx`, `blastn`, `tblastn`, `tblastx`, `blastdbcmd`, `makeblastdb`, and `blast_formatter`.

Note that these are downloaded behind the scenes in line 22 of Dockerfile.
