### ISSUE TITLE
Updated documentation for HPC integration ?

### ISSUE THREAD

**Issue by loraine-gueguen** [wurmlab/sequenceserver#445]
We are deploying sequenceserver to our infrastructure. 
First of all thanks for this great tool !

We would be interested in running the blast jobs on our HPC, instead of a local server. 

I have seen the documentation here https://sequenceserver.com/doc/#hpc and on the google forum https://groups.google.com/d/msg/sequenceserver/Ed05cYtHyPY/cMNYUxeaBQAJ.

But it seems outdated (2016), and the code has changed, the line number indicated doesn't exist anymore:
>  And then modify L67 of lib/sequenceserver/blast.rb to
> `system("/path/to/script #{rfile.path} #{efile.path} #{command}")`

Do you have an updated documentation for HPC integration ?
Is it easily achievable ?

Thanks in advance.

**Comment by yeban** [comment]
The documentation needs updating indeed.

For version 2.0, add the following at [line 51 in `blast/job.rb`](https://github.com/wurmlab/sequenceserver/blob/master/lib/sequenceserver/blast/job.rb#L51):

```
def run 
  system("/path/to/script #{stdout} #{stderr} #{command}")
end
```

Please let me know if that works. I will then update the website.

**Comment by loraine-gueguen** [comment]
We have deployed the last stable release of sequenceserver (1.0.12) and I find out that I was not looking at the right version of code on github: on the tag 1.0.12, the given line number still exists (L67 of lib/sequenceserver/blast.rb). Sorry for the mistake...

But I thank you for the update for version 2.0 !

What are the new features in this version ? Is there a planned release date for this version ?

**Comment by yeban** [comment]
Sorry I have been slow to response lately. This google group thread is the best place to learn about version 2.0: https://groups.google.com/d/msg/sequenceserver/2G4_jdAr4-k/tkbRaCovAAAJ

You can try a beta release of version 2.0 now. The stable release should follow hopefully in 2-4 months time.

**Comment by loraine-gueguen** [comment]
ok. Thanks!

**Comment by loraine-gueguen** [comment]
> 
> 
> The documentation needs updating indeed.
> 
> For version 2.0, add the following at [line 51 in `blast/job.rb`](https://github.com/wurmlab/sequenceserver/blob/master/lib/sequenceserver/blast/job.rb#L51):
> 
> ```
> def run 
>   system("/path/to/script #{stdout} #{stderr} #{command}")
> end
> ```
> 
> Please let me know if that works. I will then update the website.

I have tested with 2.0.0rc4 and that works. 
Moreover, regarding the script proposed in https://groups.google.com/d/msg/sequenceserver/Ed05cYtHyPY/cMNYUxeaBQAJ, it is needed to add 2 more `sed` commands to handle list_outfmt options:
`param=`echo "$@" | sed "s/\-db\ /\-db\ \'/" | sed "s/\ \-query\ /\'\ \-query\ /" | sed "s/\-outfmt\ /\-outfmt\ \'/" | sed "s/\ \-num_threads\ /\'\ \-num_threads\ /"`
Cheers

**Comment by yeban** [comment]
Thanks!
