### ISSUE TITLE
Alignment line breaks are not in the right places

### ISSUE THREAD

**Issue by GeneDesign** [wurmlab/sequenceserver#455]
I just upgraded to the latest sequenceserver from 1.0.11 (I think its the latest? I used the command clone https://github.com/wurmlab/sequenceserver.git today. The main thing i had to change was going from blast 2.9 to 2.10, so whichever version required that.)

Everything is working, but the test alignments are breaking lines in the following fashion:

![Screen Shot 2020-02-28 at 6 22 07 PM](https://user-images.githubusercontent.com/109966/75599195-6f0d0400-5a57-11ea-8bf2-68515df17fd9.png)

Am I doing something wrong?

**Comment by yeban** [comment]
I just pushed some changes that might fix this. Can you update your clone (`git pull`) and try again? Be sure to do a hard refresh in the browser (Ctrl-Shift-R; or clear cache) so that old sources are cleared.

**Comment by GeneDesign** [comment]
Much better, thank you

![Screenshot 2020-02-29 15 12 36](https://user-images.githubusercontent.com/109966/75616458-ef8a3e00-5b05-11ea-9a00-6ba976541fac.png)
