### ISSUE TITLE
Problem installing v.2.0

### ISSUE THREAD

**Issue by michaelbroe** [wurmlab/sequenceserver#460]
(I'm a ruby newbie..)

```
$ gem install --pre sequenceserver
Fetching: rack-2.2.2.gem (100%)
ERROR:  Error installing sequenceserver:
        rack requires Ruby version >= 2.3.0.
$ ruby --version
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

**Comment by michaelbroe** [comment]
Wait, this looks an issue on my end with interactions between conda envrionments and the sudo path. You can close this until I sort out the mess.

Cheers,
Michael

**Comment by yeban** [comment]
No problem. Glad to see people trying out the candidate 2.0 release!
