### ISSUE TITLE
Can not redirect to original blast page by refreshing the web page

### ISSUE THREAD

**Issue by zhangxiang36** [wurmlab/sequenceserver#462]
When a job is done, I want to do another job. In ncbi blast webapplication for example, i can just click backward button on the browser to enter the request page. But in sequenceserver 2.0, this can't be done. 

![image](https://user-images.githubusercontent.com/35088426/80555297-770b0500-8a02-11ea-9503-5cf15e2b45a5.png)

 As I can see, when i go back to previous page, there is no organism can be shown and selected. In addition, I got an 404 code in the chrome dev network pannel, "http://path-to-my-server/searchdata.json?job_id=blastServer/3de2ce4c-f168-40b4-85a1-ffe18373500f"

![image](https://user-images.githubusercontent.com/35088426/80555428-d406bb00-8a02-11ea-9e22-a41c53286739.png)

I really just want to back to this initialized page as shown below, how can i do this simplly? Is this a bug?
![image](https://user-images.githubusercontent.com/35088426/80555708-a79f6e80-8a03-11ea-8e83-871aac76db65.png)

**Comment by zhangxiang36** [comment]
By the way, now I only can do another blast job by close and reopen my browser .

**Comment by yeban** [comment]
Hi. This does look like a bug. Thanks for bringing it to our attention. Looks like I had forgotten about sub-uri deployments when implementing back button functionality. I am sorry about that.

I have applied a potential fix in the codebase. However, I don't have a SequenceServer setup similar to yours so I am unable to test it rapidly. I was wondering if you might be able to test the fix? How did you install SequenceServer? Did you use `gem install` or `git clone`?

**Comment by zhangxiang36** [comment]
Sorry for late reply. I install it from gem, not git clone, thanks!

**Comment by yeban** [comment]
Okay, I have made the fix available in a gem release: run `gem install --pre sequenceserver` to update and try it out. Please let me know if that fixes the problem. Thanks!

**Comment by zhangxiang36** [comment]
I think it's totally OK now, that's what I want exactly. Thanks a lot. 
By the way, I highly recommend that the blast results can be shown in a new blank page after clicking blast button, as an optional choice.

**Comment by yeban** [comment]
I am glad the issue is resolved. Thanks for testing the fix and letting us know.

Ability to optionally show BLAST results in a new page (tab) is something we want as well. Not sure how soon we can make it happen though. I have opened a ticket to track the request (#467). Feel free to subscribe to the ticket so you can be notified when it is implemented.
