### ISSUE TITLE
2.0 and legacy database format

### ISSUE THREAD

**Issue by enuggetry** [wurmlab/sequenceserver#463]
Version 2.0 question:
How can it be configured to support legacy database formats?
Can it be configured to support any format through v5?

**Comment by yeban** [comment]
Relaxing BLAST version constraint to allow 2.9 would also simplify things for @Bjoernsen (#458). @yannickwurm I suppose you would be on board with the above change as you have already argued for relaxing BLAST version constraint in a different context?

**Comment by yannickwurm** [comment]
>  even if the original FASTA files aren't around one can extract the sequences out of the BLAST databases and recreate the database in the newer format. 

I suggest that our documentation should include an example command for doing this (either for one, or for many databases). 

>  I am willing to relax version check so that SequenceServer works with BLAST 2.9 or higher automatically without individual users having to make the change themselves. The default behaviour would still be to download BLAST 2.10, but you would be able to download BLAST 2.9 yourself and tell SequenceServer to use that instead.

I think this is an appropriate thing to do. Can we detect which database version it is and print out a warning, encouraging users to transition to the newer database format? My guess is that we could want to support v4 databases/ blast 2.9 with seqserv 2.0. This can facilitate transition to what we feel is a hugely improved sequenceserver architecture. 

However, we wouldn't want to carry on supporting old systems indefinitely. We thus could make seqserv 2.1 and later require blast 2.10 or newer.

**Comment by enuggetry** [comment]
Dealing with a ton of legacy databases.  It's a load.  --thanks.

**Comment by yeban** [comment]
The fix has landed in the master branch. You using `git clone` or `gem install`?
