### ISSUE TITLE
Database not found if the name ends with 2 digits or more, in release 1.0.13

### ISSUE THREAD

**Issue by loraine-gueguen** [wurmlab/sequenceserver#465]
The issue is explained here: https://groups.google.com/d/msg/sequenceserver/jVOLbp2XlkQ/ZvAQqspiAwAJ

The database files are the following:
genus-sp_xx32.nhr
genus-sp_xx32.nin
genus-sp_xx32.nog
genus-sp_xx32.nsd
genus-sp_xx32.nsi
genus-sp_xx32.nsq

I have found were the issue comes from: sequenceserver thinks that this is a multipart database whereas it is not, because of the regex used here: https://github.com/wurmlab/sequenceserver/blob/e25c96a12aa9beaed0e475ed0436f62d8c6e679b/lib/sequenceserver/database.rb#L218

**Comment by yeban** [comment]
Fixed by #466
