### ISSUE TITLE
Ability to optionally open results in a new tab

### ISSUE THREAD

**Issue by yeban** [wurmlab/sequenceserver#467]
This has come up a few times, most recently in #463 

I suppose a checkbox that toggles `target="_blank"` attribute on the search form would suffice. The biggest consideration is the positioning of the checkbox and if we may want to make a keyboard shortcut possible.

**Comment by yannickwurm** [comment]
My preference is for a keyboard shortcut (command or control -click) rather than a checkbox which indeed creates clutter
