### ISSUE TITLE
running sequenceserver in docker- echo status and disable questions

### ISSUE THREAD

**Issue by mjy** [wurmlab/sequenceserver#468]
I'm running rc3 via docker-compose.  Two thoughts:

* Can the container echo a line to the log when it is ready for connections?  There is seemingly a long lag where I get 502 gateway errors, which suddenly go away and I'd like to debug whether this is my setup or SS just taking a long time to boot
* I see there is a question prompt in the container ("Do you want to be notified of SequenceServer releases and a...").  Seems like this could get in the way of automated deployment, perhaps disable, or provide options for running the container without being prompted?  I.e. when I do `docker-compose up`, then I want to just run SS.

**Comment by mjy** [comment]
Amending this- I see now `[2020-05-09 17:07:04] WARN  Will listen on all interfaces (0.0.0.0). Consider using 127.0.0.1 (--host option).` which can be a proxy for "I'm ready", but not *quite* the same message I'm thinking of... and in theory not echoed if host option is used.

**Comment by yeban** [comment]
I hear you on printing a more sensible 'ready for connection' message - will have to see if the underlying server framework allows for that.

Thanks for raising both the issues, especially so for the second one - the prompt is a very recent addition and I did not have the chance to consider how it might impact docker setup.

I will try to get back to you with fixes later this week - I want to be on top of docker stuff before the stable 2.0 release.

**Comment by yeban** [comment]
Hi. Thanks for being patient.

Regarding the first question, SequenceServer does print a message when it is ready. It is of the form 'SequenceServer is ready. Go to <url> in your browser and start BLAST-ing.' If you are not seeing this message, then this might be specific to your docker-compose setup. Note that this message is printed to stdout while the logger (e.g., "WARN Will listen on all interfaces ...") is printed to stderr. Could it be this distinction that you are not seeing the ready message?

Regarding the second point, I have updated the docker file to disable the prompt (see the commit linked above). Docker hub will automatically build the updated image once I push a new release. But if you could test beforehand and let me know, that would be great.

**Comment by yeban** [comment]
> Regarding the second point, I have updated the docker file to disable the prompt (see the commit linked above). Docker hub will automatically build the updated image once I push a new release. 

This is available on docker hub now if you want to give it a try. Please reopen the issue if the problem persists.
