### ISSUE TITLE
Error in gem installed seqserver while running clast search over nginx

### ISSUE THREAD

**Issue by peeyushsahu** [wurmlab/sequenceserver#474]
Hello,

First thank you to developers for creating a nice wrapper. I am trying to run sequenceserver after installing with gem with nginx. I can easily access it but when a query is ran it throws below error:

NoMethodError - undefined method `root' for nil:NilClass:
/var/lib/gems/2.5.0/gems/sequenceserver-1.0.14/lib/sequenceserver/blast/report.rb:38:in `generate'
/var/lib/gems/2.5.0/gems/sequenceserver-1.0.14/lib/sequenceserver/blast/report.rb:21:in `initialize'
/var/lib/gems/2.5.0/gems/sequenceserver-1.0.14/lib/sequenceserver/blast.rb:96:in `new'
/var/lib/gems/2.5.0/gems/sequenceserver-1.0.14/lib/sequenceserver/blast.rb:96:in `run'
/var/lib/gems/2.5.0/gems/sequenceserver-1.0.14/lib/sequenceserver/routes.rb:135:in `block in <class:Routes>'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/head.rb:13:in `call'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
/var/lib/gems/2.5.0/gems/sequenceserver-1.0.14/lib/sequenceserver.rb:96:in `call'
/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/handler/webrick.rb:88:in `service'
/usr/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'
/usr/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'
/usr/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'

thank you in advance.

best,
Peeyush

**Comment by yeban** [comment]
I think you would get this error if BLAST fails to produce any output. Did you compile BLAST yourself?

**Comment by peeyushsahu** [comment]
No, I did not compile but downloaded the blast-2.10 from ncbi website. To mention, I get error only when running via nginx. when I run on localhost it gives me a result.

**Comment by peeyushsahu** [comment]
Hi, 
I think i found the problem, my system is not connected to internet. sequence server is throwing error when converting result in xml format.
`./blast_formatter -archive /tmp/sequenceserver_blast_result20200630-3985-fcttb4 -outfmt 5 -out /tmp/sequenceserver-xml_report.xml20200630-3985-1iut3nq
`
Error:
Warning: (302.106) [SOCK_gethostbyname]  Failed gethostbyname_r("www.ncbi.nlm.nih.gov") {error=200001,Host not found}
Error: (302.22) SSOCK#1000[?]@:443: [SOCK::Connect]  Failed SOCK_gethostbyname("www.ncbi.nlm.nih.gov")
 
Is there a way not to connect and finish the job?

**Comment by yeban** [comment]
Ah, no - it's a bug in BLAST 2.10 (see #458). You can download BLAST 2.9 and use that with SequenceServer though.

**Comment by peeyushsahu** [comment]
That worked. Thanks for the input.
