### ISSUE TITLE
Upper query field not available after a blast search

### ISSUE THREAD

**Issue by Tom-A-MD** [wurmlab/sequenceserver#492]
My colleague installed v 2.0, after we have used v 1.0 for some years.  There is a small issues - as installed, after the blast, the screen shows results, but the query field is gone.  The upper query field was very useful for three reasons:
1)  We can use the same query to blast other assemblies (as we have a number that are available on the webpage)
2)  We can reinitiate a blast with another query, with the same selection of assemblies 
3)  A totally new blast can be launched from the same page.  

I don't even see a return to Blast page button.  Is there an option that needs to be toggled in the setup of SequenceServer?

Thanks much

**Comment by yeban** [comment]
Hi, thanks for trying out version 2.0. You can return to the blast page by clicking on the back button of your browser. The form remains filled out so you can do all of the above as before.

I understand your confusion about the lack of a visible back / edit search button. We intend to add one. We will also plan to add an option in the search form to open BLAST results in a new tab. This can make workflows 1 and 2 more effective as you would be able to launch multiple searches with different query-database combinations and compare the results side by side.

I hope that helps.
