### ISSUE TITLE
SequenceServer image size

### ISSUE THREAD

**Issue by nathanweeks** [wurmlab/sequenceserver#495]
There was some effort to reduce the image size of SequenceServer in https://github.com/wurmlab/sequenceserver/issues/413. The resulting image (at commit e14aaf621899e2e0635cc50405c4051ec83ed56d) still clocks in at 809 MB (uncompressed, per `docker images`) on my workstation. With a few optimizations, I observed a decrease in image size to 211MB (uncompressed); this included expanding the scope of .dockerignore such that it copied only the essentials---the .git directory alone clocks in at ~49M---or at least, what looked like it might be essential:

```
*
!Gemfil*
!bin
!config.ru
!lib
!public
!sequenceserver.gemspec
!views
```

and using a multistage build that trimmed some of the packages included in the final image, as well as used the BLAST executables from the official ncbi/blast:2.10.0 image, which are dynamically linked (and each much smaller than the statically-linked executables downloaded from ftp.ncbi.nlm.nih.gov): 

```
FROM debian:buster-slim AS builder

LABEL Description="Intuitive local web frontend for the BLAST bioinformatics tool"
LABEL MailingList="https://groups.google.com/forum/#!forum/sequenceserver"
LABEL Website="http://www.sequenceserver.com"

RUN apt-get update && apt-get install -y --no-install-recommends \
        ruby ruby-dev build-essential curl gnupg git wget \
        zlib1g-dev && rm -rf /var/lib/apt/lists/*

COPY . /sequenceserver
WORKDIR /sequenceserver
# Install bundler, then use bundler to install SequenceServer's dependencies
RUN gem install bundler && \
        bundle install --without=development

FROM debian:buster-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
        ruby curl libgomp1 liblmdb0 && rm -rf /var/lib/apt/lists/*

RUN mkdir -p ~/.sequenceserver && \
    touch ~/.sequenceserver/asked_to_join \
    && ln -s /bin/true /usr/bin/git # "git ls-files" is called in sequenceserver.gemspec

COPY --from=ncbi/blast:2.10.0 /blast/lib /blast/lib/
COPY --from=ncbi/blast:2.10.0 /blast/bin/blast_formatter /blast/bin/
COPY --from=ncbi/blast:2.10.0 /blast/bin/blastdbcmd /blast/bin/
COPY --from=ncbi/blast:2.10.0 /blast/bin/blastn.REAL /blast/bin/blastn
COPY --from=ncbi/blast:2.10.0 /blast/bin/blastp.REAL /blast/bin/blastp
COPY --from=ncbi/blast:2.10.0 /blast/bin/blastx.REAL /blast/bin/blastx
COPY --from=ncbi/blast:2.10.0 /blast/bin/makeblastdb /blast/bin
COPY --from=ncbi/blast:2.10.0 /blast/bin/tblastn.REAL /blast/bin/tblastn
COPY --from=ncbi/blast:2.10.0 /blast/bin/tblastx.REAL /blast/bin/tblastx
COPY --from=builder /usr/local/bin/ /usr/local/bin/
COPY --from=builder /var/lib/gems /var/lib/gems
COPY --from=builder /sequenceserver/ /sequenceserver/
WORKDIR /sequenceserver

ENV PATH=/blast/bin:${PATH}
VOLUME ["/db"]
EXPOSE 4567

CMD ["bundle", "exec", "bin/sequenceserver", "-d", "/db"]
```

The above Dockerfile has only been lightly tested, and is a bit more "verbose" than what might be desired, but I'll throw it out there for consideration in case any of it might give useful ideas (if not, feel free to close this issue).

**Comment by yeban** [comment]
The image size reduction is impressive. I can see that using dynamically-linked binaries reduces around 215 Mb and .dockerignore  reduces another ~100 Mb. So the rest must be a result of multistage build - I do see a difference of 244 Mb between the `/usr` dir in your vs our images. But I don't fully understand how it works: why is the second `apt-get install` line required - isn't copying `/usr/local/bin` from `builder` enough? Why copy `sequenceserver` first to builder and then from builder to final? I am also surprised how things are working without copying `/usr/lib` - I suppose the bulk of install build-essentials package is in `/usr/lib` but we only need the executable `make`. Could you elaborate a bit? Do you have a pointer, like a nice blog post or a well documented standard Dockerfile, that uses multi-stage build in this manner?

In a quick test I didn't see any problem in trying to run sequenceserver, so I am very much interested in this change. Would you mind sending the change as a pull-request so that you are identified as the author of the change? Also, is it possible to extract BLAST version into a variable so that it is a one line change when we need to update BLAST version?

**Comment by nathanweeks** [comment]
> why is the second apt-get install line required - isn't copying /usr/local/bin from builder enough?

ruby and curl are installed into /usr/bin; /usr/local/bin contains scripts from `gem install bundler` and `bundle install --without`.

> Why copy sequenceserver first to builder and then from builder to final? 

Probably only a subset is needed for the `gem install bundler && bundle install --without=development`, though I'm not a ruby guru, and in the interest of expedience (or laziness) I just copied the entire sequenceserver directory. It would be more convenient for sequenceserver development, however, if ruby dependency installation could be isolated to the first build stage, and any sequenceserver code copied in the second (otherwise, changing a source file would cause the `gem install bundler && bundle install --without=development` step to be repeated unnecessarily on the next `docker build`). If you could identify a minimal set of file(s) that would be required for the "builder" stage, it would be appreciated; otherwise, I could experiment as I have time.  

> I am also surprised how things are working without copying /usr/lib - I suppose the bulk of install build-essentials package is in /usr/lib but we only need the executable make.

Is `make` needed after `gem install bundler && bundle install --without=development`?

> Do you have a pointer, like a nice blog post or a well documented standard Dockerfile, that uses multi-stage build in this manner?

There might be some good tutorials out there, but it seems the approach really varies by application / software stack. I've done a number of multistage builds, but this is the first time with both ruby and the ncbi/blast docker image, and it has been a bit of a learning experience.

> Would you mind sending the change as a pull-request so that you are identified as the author of the change? Also, is it possible to extract BLAST version into a variable so that it is a one line change when we need to update BLAST version?

Sure thing; I'll plan to have a go at parameterizing the BLAST version, do a bit of testing / tuning the first stage, and submit a PR (will likely have some days to collect any input/feedback beforehand).

**Comment by nathanweeks** [comment]
I took a stab at this in #498, which also attempts to install dependencies in the first stage, and copy code in the final stage, so, e.g., a change in a source file during development doesn't bust the build cache and require all dependencies to be reinstalled. To simplify the "builder" stage, I used the ruby `Dir` instead of `git ls-files`; the latter is apparently [not recommended](https://packaging.rubystyle.guide/#using-git-in-gemspec) anymore. But I'm admittedly uncertain if I implemented this part correctly, or if there are unanticipated side effects; corrections may be warranted (and would be appreciated!)

Given the nature of this project, I thought it would be appropriate to use the [ruby Docker Official image](https://hub.docker.com/_/ruby), as it would provide tighter control over the ruby version used (at the cost of some extra size in the final image: ~270 MB uncompressed, though perhaps there are some files in spec/ that can be excluded from the final image?).

**Comment by yeban** [comment]
`spec/` is already excluded from the image by your `.dockerignore`. So the increase in image size is likely the result of changing the base image. Indeed you will see considerable difference in the size of `/usr` in the images built using Dockerfile proposed here and in the PR. I don't mind the change to the official ruby docker image.

**Comment by yeban** [comment]
I learnt a great deal from this issue and the accompanying pull-request. Thanks!
