### ISSUE TITLE
Docker imge build error using BuildKit

### ISSUE THREAD

**Issue by nathanweeks** [wurmlab/sequenceserver#502]
It turns out that the new Dockerfile introduced by https://github.com/wurmlab/sequenceserver/pull/498 doesn't build when using [BuildKit](https://github.com/moby/buildkit), which is helpful for performant multistage builds now, and is slated to become the default Docker image builder in the near future:

```
$ DOCKER_BUILDKIT=1 build -t sequenceserver .
...
 => CACHED [stage-2 13/16] WORKDIR /sequenceserver
 => CACHED [stage-2 14/16] COPY . .
 => ERROR [stage-2 15/16] RUN echo 'n' | bundle exec bin/sequenceserver -s -d /db
------                                                                                                                                   
 > [stage-2 15/16] RUN echo 'n' | bundle exec bin/sequenceserver -s -d /db:
#26 0.451 stty: 'standard input': Inappropriate ioctl for device
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c echo 'n' | bundle exec bin/sequenceserver -s -d /db]: runc did not terminate sucessfully
```
The `inappropriate ioctl for device` error still displays using the default (legacy) builder, but the build continues.

Not sure how to fix---maybe `sequenceserver -s -d /db` shouldn't prompt a user to search for FASTA files in a `-d DB` directory that doesn't have any BLAST databases unless the `-i/--interactive` option is set?

**Comment by yeban** [comment]
Thanks for looking into this. You can test the idea that `sequenceserver -s -d /db` line is causing the issue by removing it and building the image. What that line does is to create a default config file (`/root/.sequenceserver.conf`) but with `:database_dir:` option set to `/db`.

If the image builds successfully, you will want to run as `docker run ... image_name sequenceserver -d /db` to have the same effect as the config file.

I had good reasons to add that config file to the image, so if you are right about the cause of the issue we will ideally want another way to add the file to the image.

Sorry, `-i` option does something completely different than what you think it does.

**Comment by nathanweeks** [comment]
Removing the `RUN echo 'n' | bundle exec bin/sequenceserver -s -d /db` when using BuildKit does result in the image building successfully.

Thanks for the clarification regarding the `-i` option. I'm not sure offhand how to resolve this without modifying the sequenceserver code; would it be possible to have an option(s) (or environment variable(s)) that facilitates such scripted use?
