### ISSUE TITLE
Wrong identity values in summary

### ISSUE THREAD

**Issue by EtienneBucher** [wurmlab/sequenceserver#506]
I have the following instance of Sequencesever running:
SequenceServer 2.0.0.rc7 using BLASTN 2.10.1+
Stangely enough, perfect hits never reach 100% in the summary table of hits:

Query coverage (%) | Total score | E value | Identity (%)
1. | rice-Chr2 | 100 | 34779 | 0 | 79

However in the alignment I get the right values:
a. Score: 7479.86 (8294), E value: 0, Identity: 4147/4147 (100%), Gaps: 0/4147 (0%), Strand: + / -

I have the same issue with at least two different databases.
Any idea what could be wrong in my setup?

Cheers,
Etienne

**Comment by yeban** [comment]
Hi Etiene. The table shows average identity of all matches (alignments) to a database sequence. The value in table would be 100% if there is only one match to the database sequence with identity of 100%. Does that help?

**Comment by EtienneBucher** [comment]
Thank you for your quick reply! 
Is that the expected behaviour? For me it is quite confusing to see these results when I blast against complete genomes. This may hide an excellent hit on a chromosome due to many other bad hits on the same chromosome.
Is there a way to have all the hits listed separately? Meaning that in the table I could have several Chr1 hits listed (e.g. a,b,c) to more easily navigate to the hits that may be of interest?

**Comment by yeban** [comment]
> Is that the expected behaviour? For me it is quite confusing to see these results when I blast against complete genomes. This may hide an excellent hit on a chromosome due to many other bad hits on the same chromosome.

I think that's fair. Let me see how we can best fix that in the next week or so.

> Is there a way to have all the hits listed separately? Meaning that in the table I could have several Chr1 hits listed (e.g. a,b,c) to more easily navigate to the hits that may be of interest?

No. Would this still be important to you if the table showed the identity of the best hit? Just trying to understand.

**Comment by yeban** [comment]
Sorry, I got wrapped up working on my thesis. I am going to need a 3-4 more weeks before I can resume work on sequenceserver. Thanks for being patient.

**Comment by yannickwurm** [comment]
Hi just to follow-up - I agree that we should revert to the NCBI default of showing the %id for the top HSP for that database sequence. (this is for example, because we wouldn't want the score of the best hit to be pulled down by a diverged homolog)
This way the info we show for %id is also consistent with the info we show for evalue and bitscore.
