### ISSUE TITLE
sort databases in categories

### ISSUE THREAD

**Issue by dsmlab** [wurmlab/sequenceserver#507]
Hi there,
On the search page, could you group the databases in different categories that, to keep things simple, would correspond to the directory structure in the database folder?
The idea would be to have some kind of dropdown or folding menu in place of radio buttons and allow users to nicely navigate across a large range of databases, possibly also selecting all the databases of a given group by clinking on the group

**Comment by yeban** [comment]
Sorry, it's not currently possible. The idea has been discussed before (#307, #29) but there was always something more important on the todo list so it never got done.
