### ISSUE TITLE
Cant get fasta list of hits, sequenceserver 2.0

### ISSUE THREAD

**Issue by wpmitchell** [wurmlab/sequenceserver#519]
Hi --

blastp rexecutes fine, but I cannot get fasta of result, neither the complete list, nor the individual fasta sequences. 
I get there ruby errors at command line when I try to download fasta sequence(s)
2021-02-15 10:38:18 - SequenceServer::CommandFailed - SequenceServer::CommandFailed:
	/usr/local/lib/ruby/gems/2.7.0/gems/sequenceserver-2.0.0.rc8/lib/sequenceserver/sys.rb:83:in `sys'
	/usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/forwardable.rb:235:in `sys'
	/usr/local/lib/ruby/gems/2.7.0/gems/sequenceserver-2.0.0.rc8/lib/sequenceserver/sequence.rb:203:in `run'
	/usr/local/lib/ruby/gems/2.7.0/gems/sequenceserver-2.0.0.rc8/lib/sequenceserver/sequence.rb:182:in `initialize'
	/usr/local/lib/ruby/gems/2.7.0/gems/sequenceserver-2.0.0.rc8/lib/sequenceserver/routes.rb:135:in `new'
	/usr/local/lib/ruby/gems/2.7.0/gems/sequenceserver-2.0.0.rc8/lib/sequenceserver/routes.rb:135:in `block in <class:Routes>'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `call'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (3 levels) in route!'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block (2 levels) in route!'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `catch'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `each'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
	/usr/local/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/deflater.rb:44:in `call'
	/usr/local/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
	/usr/local/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
	/usr/local/lib/ruby/gems/2.7.0/gems/sequenceserver-2.0.0.rc8/lib/sequenceserver.rb:114:in `call'
	/usr/local/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/handler/webrick.rb:95:in `service'
	/usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/webrick/httpserver.rb:140:in `service'
	/usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/webrick/httpserver.rb:96:in `run'
	/usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/webrick/server.rb:307:in `block in start_thread'

**Comment by mptrsen** [comment]
Also having this problem.

**Comment by yeban** [comment]
Sorry for the slow response. I think this is an edge case. Can you tell me the id of the sequence that causes this problem? Also, did you BLAST one database or two or more when you encountered this problem?

**Comment by WardDeb** [comment]
Hi Yeban,

To elaborate on this (since @mptrsen 's problem and mine are the same, same sequenceserver instance):

I don't think it's query sequence related, since we experienced this with different sets of queries. As an example, we get this error consistently when using the first 15 foxn1 hits in NCBI refseq as queries. 

The error only occurs when using two (perhaps also with more, but haven't tested this) databases. The same query set works if I blast against the two databases separately. 

Kind regards,

Ward

**Comment by mptrsen** [comment]
@WardDeb elaborated on the issue, I wanted to add a link to queries: https://www.ncbi.nlm.nih.gov/nuccore/?term=foxn1+AND+srcdb_refseq%5BPROP%5D -- use any one of those or download them all as FASTA. Thanks for looking into this.

**Comment by yeban** [comment]
I am not able to reproduce the issue. I downloaded first three sequences from the aforementioned link and tried BLAST-ing the first sequence to a database of the three sequences.

What do you compare the foxn1 genes to?

**Comment by yeban** [comment]
It is the id of the database hits that is important for FASTA download. Do you face problem consistently with one particular database or anytime you search more than two databases at once? Do you face this problem with particular database hits or all of them?

**Comment by wpmitchell** [comment]
Hi —

In my case its a locally created BLAST DB. I can perform BLAST searches through the app fine, but cannot download the 
fasta sequences of hits.

Thanks !

Wayne

**Comment by WardDeb** [comment]
Hi Yeban,

Thanks for looking into it.
We also use custom databases, with roughly 120 million (relatively small) sequences per database. The problem seems, at least for us, limited to searching against two specific databases. The FASTA download works when blasting against the databases separately, but gives the aforementioned error when we blast against both databases at the same time. It also seems database specific, since a search against two other databases seems to work just fine.

Hope this helps.

Kind regards,

Ward

**Comment by yeban** [comment]
@WardDeb Right, can you share one or two sequences (or just the sequence ids) from the problematic databases with me? Alternatively, tell me if I am right that the problematic databases are sequenced reads and I will try to test with standard Illumina, Pacbio and Nanopore sequence ids. You can also email me the test data if you do not want to share it publicly - my email is in the README file of the repo.

**Comment by wpmitchell** [comment]
Hi — thanks for your help!

I collected all the protein sequecnes for a set of genomes fro NCBI, concatenated them into a single fasta file, and then 
used makedb to create a local blast db

the big fasta file looks like:

>Anaerotignum_propionicum_DSM1682_1 WP_004034721.1 MULTISPECIES: 50S ribosomal protein L36 [Clostridiales]
MKVRPSVKPMCEKCRIIKRKGRVMVICENPKHKQKQG
>Anaerotignum_propionicum_DSM1682_2 WP_022255363.1 MULTISPECIES: 30S ribosomal protein S21 [Anaerotignum]
MSEVKVKENESLDSALRRFKRTCARDGIMGEVRKREHYDKPSVKRKKKSEAARKRKFK
>Anaerotignum_propionicum_DSM1682_3 WP_066046472.1 hypothetical protein [Anaerotignum propionicum]
MWKTSFFPKNQEFWMLTSHVEAMGVTDRLIHSMHSKAELSKVVHSLSLACSTRQCGKIIAP
>Anaerotignum_propionicum_DSM1682_4 WP_066046474.1 DNA polymerase III subunit beta [Anaerotignum propionicum]
MKLICKKDLLLQYINIVNKAVSNRTTLPILECILLTADDKGFVLTGNDLELGIKTAAIEADILEKGEVAIEARIFNEIVR
RLNGEDVTISTNEKNAVTIVCGSSEFSIMGQGGDDFPALPEVEQNQAYTLKQNDLRNMIRQTIFSIAQDNAKPVLTGELF
EFHDEFFNIVSVDGYRISYRKNNLIQSCGKNDVIVPGKTLSELNKILSQSDEDLVSLYVTDKHILFDLGTAIMVSRLIEG
DFIRYEQSFSEDFKTEVLVDKNQMIQSLERASLVSRDNRKTPVRFQIKTKNMEITAKSDMGTAFEEISVEVEGEEISIAF
NPRYFIEALRSIDEENVKIHFTASLSPCTILPVEGDSFKYLILPLRM
>Anaerotignum_propionicum_DSM1682_5 WP_066046476.1 RNA-binding S4 domain-containing protein [Anaerotignum propionicum]
MQEVGIQTEFIKLQQILKLAGIIGQGSDARALIAEGLVYVNGEQALERGKKIRHNDVVEVKGLGSVKVVMED
>Anaerotignum_propionicum_DSM1682_6 WP_066046478.1 DNA replication/repair protein RecF [Anaerotignum propionicum]
MQISEVSLQGFRNLMEMQIKPSPGINVFYGKNAQGKTNFLESLYLCAMGRSMRTKYDWQMIGFQEEESHIRLLINKNNRK
ERIDVHLKRDTKKGIARNGVPIKKLGDLFGTLYTVVFSPEDLSLIKDGPAERRRFLDMELCQLSRVYYYDLQQYYRILKQ
RNNLLREIQKNSSLQDTLFVWDAQLIDYGERVMAARTDFLKRLDKIATEKLNALTGGLDALKIIYKPNCEPGHMEERLKR
NLQRDIYLGSTNFGPHKDDILFTIHGKDVKSFGSQGQQRTTALAARLAEIDLIREETGEDPILLLDDVLSELDERRQKYL
MESIDGLQAFLTCTGIEDAIKKYISKDNLFYVENGKIVAEDGMEKKRNA
…



after makedb, i have these files:

clostridia.pdb
clostridia.phr
clostridia.pin
clostridia.pot
clostridia.psq
clostridia.ptf
clostridia.pto



to which I point when using “sequenceserver”. BLASTP runs great, and generates
a webpage with BLAST results and FASTA buttons, but they dont work. 

So I need to add something when building the db ?

Thanks you!

Wayne

**Comment by yeban** [comment]
> So I need to add something when building the db ?

I think the `-parse_seqid` option.

**Comment by yeban** [comment]
Hello. Did you get a chance to try building the db with `-parse_seqids` option?

**Comment by mptrsen** [comment]
All our databases are built with the `-parse_seqids` option. Did you get a chance to look into this with the test data you got from @WardDeb ?

**Comment by yeban** [comment]
I did. I tried with the test data from @WardDeb and I cannot reproduce the issue if `-parse_seqids` option is used.

> after makedb, i have these files:
> clostridia.pdb
> clostridia.phr
> clostridia.pin
> clostridia.pot
> clostridia.psq
> clostridia.ptf
> clostridia.pto

If you did build using `-parseq_seqids`, you are still two files short: `.pog` and `.pos`. The next guess is that that the databases were created using BLAST+ 2.9 or older, but that is only a problem if you mix the old and new format BLAST databases (new format: created using BLAST+ 2.10 or later). That is, sequence retrieval doesn't work if you simultaneously searched an old and a new format database.

SequenceServer rc8 tries to prevent such mixing from happening. Did you not get a "One or more databases in /path are likely incompatible." message on startup? Or did you, and somehow managed to bypass it?

**Comment by mptrsen** [comment]
The clostridia datasets aren't ours but from @wpmitchell's instance.

Some of our databases are indeed old enough to have been built by BLAST <= 2.9. We'll check if this is the case and see whether the incompatibility warning was circumvented.
