### ISSUE TITLE
stats, analytics, history

### ISSUE THREAD

**Issue by enuggetry** [wurmlab/sequenceserver#524]
Is there anywhere I can find stats/analytics and histories for queries, databases, hit results per database, frequency data etc. of any type?

**Comment by yeban** [comment]
There is no direct aggregation of such data in sequenceserver, but maybe you can derive some stats from job data saved in  `~/.sequenceserver`.

**Comment by yannickwurm** [comment]
Hi @enuggetry - we provide an aggregation of that kind of info to users of the [Cloud Blast service](https://sequenceserver.com/cloud)
