### ISSUE TITLE
systemctl error

### ISSUE THREAD

**Issue by prometheusloong** [wurmlab/sequenceserver#533]
Hi, 
    I want to start the sequenceserver 2.0 auto by systemctl.  If i run sequenceserver directly by `/usr/local/rvm/gems/ruby-2.7.2/gems/sequenceserver-2.0.0.rc8/bin/sequenceserver -c /home/zcyu/.rvm/gems/ruby-2.7.2/gems/sequenceserver-2.0.0.rc8/sequenceserver.conf`. It worked.
    

    But 'systemctl start sequenceserver.service' has error like below: 
`Jun 25 18:54:12 localhost.localdomain sequenceserver[203287]: /usr/local/rvm/gems/ruby-2.7.2/gems/sequenceserver-2.0.0.rc8/bin/sequenceserver:29: syntax error, unexpected tIDENTIFIER, expecting ')'
Jun 25 18:54:12 localhost.localdomain sequenceserver[203287]: other important announcements (3-12 messages a year)? If yes,
Jun 25 18:54:12 localhost.localdomain sequenceserver[203287]: ^
Jun 25 18:54:12 localhost.localdomain sequenceserver[203287]: /usr/local/rvm/gems/ruby-2.7.2/gems/sequenceserver-2.0.0.rc8/bin/sequenceserver:29: syntax error, unexpected ')', expecting keyword_end
Jun 25 18:54:12 localhost.localdomain sequenceserver[203287]: other important announcements (3-12 messages a year)? If yes,
Jun 25 18:54:12 localhost.localdomain sequenceserver[203287]: ^
Jun 25 18:54:12 localhost.localdomain sequenceserver[203287]: /usr/local/rvm/gems/ruby-2.7.2/gems/sequenceserver-2.0.0.rc8/bin/sequenceserver:30: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
Jun 25 18:54:12 localhost.localdomain sequenceserver[203287]: please provide your email address below or press enter to
Jun 25 18:54:12 localhost.localdomain sequenceserver[203287]: ^
Jun 25 18:54:12 localhost.localdomain sequenceserver[203287]: /usr/local/rvm/gems/ruby-2.7.2/gems/sequenceserver-2.0.0.rc8/bin/sequenceserver:71: syntax error, unexpected tIDENTIFIER, expecting ')'
Jun 25 18:54:12 localhost.localdomain sequenceserver[203287]: # Search for FASTA files in database dir that haven't been
Jun 25 18:54:12 localhost.localdomain sequenceserver[203287]: ^
Jun 25 18:54:12 localhost.localdomain sequenceserver[203287]: /usr/local/rvm/gems/ruby-2.7.2/gems/sequenceserver-2.0.0.rc8/bin/sequenceserver:73: `$ ' is not allowed as a global variable name
Jun 25 18:54:12 localhost.localdomain sequenceserver[203287]: /usr/local/rvm/gems/ruby-2.7.2/gems/sequenceserver-2.0.0.rc8/bin/sequenceserver:73: syntax error, unexpected end-of-input, expecting keyword_end
Jun 25 18:54:12 localhost.localdomain sequenceserver[203287]: $ sequenceserver -m
Jun 25 18:54:12 localhost.localdomain sequenceserver[203287]: ^
Jun 25 18:54:12 localhost.localdomain abrt[203287]: detected unhandled Ruby exception in '/usr/local/rvm/gems/ruby-2.7.2/gems/sequenceserver-2.0.0.rc8/bin/sequenceserver'
Jun 25 18:54:12 localhost.localdomain systemd[1]: sequenceserver.service: main process exited, code=exited, status=1/FAILURE
Jun 25 18:54:12 localhost.localdomain abrt[203287]: can't communicate with ABRT daemon, is it running? undefined method `collect' for nil:NilClass
Jun 25 18:54:12 localhost.localdomain systemd[1]: Unit sequenceserver.service entered failed state.
Jun 25 18:54:12 localhost.localdomain systemd[1]: sequenceserver.service failed.
Jun 25 18:54:12 localhost.localdomain abrt-server[203290]: Element 'reason' is missing
Jun 25 18:54:12 localhost.localdomain abrt-server[203290]: Some data is missing, aborting`

**sequenceserver.service :**
`[Unit]
Description=SequenceServer
After=network.target

[Service]
Type=simple
User=root
ExecStart=/usr/local/rvm/gems/ruby-2.7.2/gems/sequenceserver-2.0.0.rc8/bin/sequenceserver -c /home/zcyu/.rvm/gems/ruby-2.7.2/gems/sequenceserver-2.0.0.rc8/sequenceserver.conf
Environment=SYSTEMD_LOG_LEVEL=debug
KillMode=process
Restart=on-failure
RestartSec=42s
RestartPreventExitStatus=255

[Install]
WantedBy=multi-user.target`

    I updated ruby by rvm, and installed sequenceserver by `usr/local/rvm/gems/ruby-2.7.2/gems/sequenceserver-2.0.0.rc8/bin/sequenceserver -c /home/zcyu/.rvm/gems/ruby-2.7.2/gems/sequenceserver-2.0.0.rc8/sequenceserver.conf`. 
    Maybe i should write ruby environment to systemctl file? How can i write them?

**Comment by yeban** [comment]
Hello,

I am sorry the email notification for this issue got buried deep in my inbox. Seems to me that your systemd script is loading SequenceServer using a version of Ruby that is older than 2.3.

I do not have experience with rvm to correctly advice how you can load the right Ruby environment in your systemctl file. Maybe something like: `/usr/local/bin/rvm 2.7 do /usr/local/rvm/gems/ruby-2.7.2/gems/sequenceserver-2.0.0.rc8/bin/sequenceserver -c /home/zcyu/.rvm/gems/ruby-2.7.2/gems/sequenceserver-2.0.0.rc8/sequenceserver.conf`. See https://rvm.io/set/do.

An alternative might be to write a bash script that activates the correct rvm environment/ruby (`rvm activate 2.7`?) and then calls out to SequenceServer - and use the bash script in your systemctl file.

You might also be able to resolve the issue by modifying the first/shebang line of the file `/usr/local/rvm/gems/ruby-2.7.2/gems/sequenceserver-2.0.0.rc8/bin/sequenceserver` to the correct Ruby interpreter. I do like this approach though - you may run into problems later.

I think it would be less of a hassle if you could install Ruby directly from your package manager - even relatively older versions ubuntu has Ruby 2.3 available in apt.

A semi-linked advice is to first run sequenceserver from command line and make sure everything works correctly. Make sure to do this as the same user as your systemd script. This is important to bypass any interactive prompts seqserv may have during startup.

I hope this helps.

**Comment by yeban** [comment]
(heads up - I slightly updated the previous comment to fix meaning-altering typos 🙈)
