### ISSUE TITLE
Edit search - rc8

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/sequenceserver#544]
If I select 15 databases, run a search (without opening a new page), then want to edit the search, my previous selections are lost. 
 - the sequence is retained
 - if I only select 1 database, my previous selection is retained. 

Could it be something with the length of the object that's being sent - beyond the num chars that get sent without truncation

**Comment by yeban** [comment]
This was fixed a while ago (08c1a6bdddf5206f0cdaade7f0856ba9bf46aea2). It's just that we haven't able to release this and a few other fixes in rc9 or so.
