### ISSUE TITLE
(SequenceServer::DATABASE_DIR_NOT_SET)

### ISSUE THREAD

**Issue by imane-boudell** [wurmlab/sequenceserver#546]
Dear all,

This is the second time I am installing SequenceServer and this time, I have encountered this issue, from NGINX error log file. I am setting up my sequenceserver to run for a suburl.

```
[ E 2021-09-11 21:57:51.6963 165372/T2r age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /var/lib/gems/2.7.0/gems/sequenceserver-1.0.14: The application encountered the following error: Database dir not set. (SequenceServer::DATABASE_DIR_NOT_SET)
  Error ID: 96dcf196
  Error details saved to: /tmp/passenger-error-pEllzS.ht
```

My config file looks like this:

```
---
:num_threads: 4
:bin: "/usr/bin"
:database_dir: "/home/myserver/fasta"
```

and my config.ru file:

```
require 'sequenceserver'

SequenceServer.init(:config_file => "/home/.sequenceserver.conf")

run SequenceServer
```

I am using nginx and I tried updating the permission to the directories and the error persists. I also tried passing the directory with the command with no success too. Please help!

**Comment by yeban** [comment]
It seems to me that SequenceServer cannot read your config file.

Is the path here correct? `SequenceServer.init(:config_file => "/home/.sequenceserver.conf")`

If it is, then you may want to set [`passenger_user`](https://www.phusionpassenger.com/docs/references/config_reference/nginx/#passenger_user) in your Nginx config to the user that is responsible for the config file and databases directory.

**Comment by yeban** [comment]
Did that help?
