### ISSUE TITLE
react is outdated

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/sequenceserver#556]
We should be using something much more recent

**Comment by yannickwurm** [comment]
- [ ] React.createClass is gone => use ES6 classes (a few React components are already written this way)
- [ ] React.render is ReactDOM.render. ReactDOM needs to be imported separately
- [ ]Update React to latest
- [ ] Do something about JSPM too (but not SystemJS)
- [ ]showErrorModal should be explicitly modelled as Function-as-Component
    - [https://blog.pixelingene.com/2017/09/the-common-patterns-of-react/#higher-order-components](https://blog.pixelingene.com/2017/09/the-common-patterns-of-react/#higher-order-components)

**Comment by yannickwurm** [comment]
- [ ] There is a different issue about potentially modularising code. That is independent of updating our basic tooling.

**Comment by salisshuaibu11** [comment]
I would like to contribute.

**Comment by sergiicherpak** [comment]
Hello, @yannickwurm 
Sorry, my computer used for Upwork has been crashed suddenly this morning, it maybe difficult to communicate via Upwork today.
I will fix it today.
I will appreciate if you understand me.
Thank you.

**Comment by yannickwurm** [comment]
Hiya, 
so @Lazy-poet has been doing this migration work. He's made huge progress. We also concluded that unit tests are needed for our JS things, and that RTL [React Testing Library] is the right approach for this. Now in trying to replace JSPM he hit a hurdle with the ruby integration. I'm copying from our other message thread.

> First, I attempted to include jest and RTL into the project, but apparently, jest cannot resolve modules installed by jspm, so it was impossible to use. I then went ahead to convert all module installations to use npm, but then, trying to make SystemJS work with npm was another hassle, which leaves me with the option of migrating SystemJS to webpack. It was quite challenging, but I was able to set it up completely. another challenge was, some of the modules installed with jspm aren’t available on the nom registry, so I had to manually include them (2 of them).
> Now, I have completely set it up, wrote a first test which passes, and the ui also works quite fine 
> Concerning the capybara_spec test, I'll like to know how '$" is meant to be included, because I get the error '$' is not defined when running the tests, so I'm presuming it's no longer loading jquery correctly. If I understand how jquery is being injected to it, then I'll know where to look to fix it.

Screenshots of successful JS test and failing ruby/rspec test: 
<img width="574" alt="Screenshot 2022-04-30 at 17 40 11" src="https://user-images.githubusercontent.com/150113/166218800-42820976-a94f-4eac-98f2-5e75d5e1b470.png">

<img width="756" alt="Screenshot 2022-04-30 at 17 40 32" src="https://user-images.githubusercontent.com/150113/166219329-8c8f32a2-8cdb-4ec8-a094-7eab13942758.png">

@yeban or @ikk0v could you help to overcome this issue?  

I think code is at https://github.com/Lazy-poet/sequenceserver or webpack/npm branch

**Comment by yannickwurm** [comment]
(brief followup coming from @lazy-poet as some of what I wrote is outdated)

**Comment by Lazy-poet** [comment]
Hi all, so after making some changes (I had to manually declare jquery's $ as a global variable which wasn't required while running it locally on my machine), the initial error has disappeared, and now I'm left with 2 types of error, as shown in the images below


<img width="353" alt="Screenshot 2022-05-02 at 11 42 10" src="https://user-images.githubusercontent.com/70343818/166222781-e9ccbfa4-f918-4580-8de7-6d07d632a9e4.png">
<img width="759" alt="Screenshot 2022-05-02 at 11 42 00" src="https://user-images.githubusercontent.com/70343818/166222791-a536cbb5-1e12-4612-b9b2-be079346dd96.png">

**Comment by ikk0v** [comment]
@Lazy-poet those errors from git@github.com:Lazy-poet/sequenceserver.git form right? (not from the main repo?)

**Comment by ikk0v** [comment]
do you guys have any ideas on how to fix this?

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/8004422/166282175-a58e969d-b397-4d45-85e5-2248e1b41c72.png">

(it get this when trying to build the app from the fork locally)

**Comment by Lazy-poet** [comment]
Oh yes, I just confirmed that the view files try to use the js files loaded by SystemJS in development mode. I have now modified the view files to use the build version in both development and production mode. You can pull again to see

**Comment by ikozakov** [comment]
![image](https://user-images.githubusercontent.com/8004422/166414258-f3f38ac8-40fd-4cc4-82c7-3bfb60548e4e.png)

This error comes from here:

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/8004422/166414297-c69d5857-d5df-4c83-9c23-860c529f44b6.png">

We have 2 databases with the same name. `Capybara#check` method doesn't know which one to select. I'm not sure what changed here, but that's where the issue came from.

I'll see how to fix it.

**Comment by ikozakov** [comment]
hmm, I cannot easily compare the main and fork repo, but, maybe you have any ideas why the fork would display 2 DB with the name "funky ids (v5)"?

Here is how it looks on the main repo:
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/8004422/166415316-f44268ec-abb2-4406-b9d4-a4a1c2e875a7.png">

I run the same scenario:
`rspec -e "can download FASTA even if the hit ids are funky"`

But you can see that the list of DBs is displayed differently if to compare the main and the fork.

**Comment by yannickwurm** [comment]
Hmmm @ikozakov  - there may be an issue with the css cache leading to a mix of old and new components. Does it hold if you clear cache / do private browsing in different browser?

**Comment by ikozakov** [comment]
> over here, these are the dbs I can see, running on same forked repo


@Lazy-poet what scenario are you running?
is it this one `rspec -e "can download FASTA even if the hit ids are funky"`?

**Comment by ikozakov** [comment]
> Does it hold if you clear cache / do private browsing in different browser?

capybara/selenium uses a clean browser for each test run, so it shouldn't be the problem, but let me check

**Comment by Lazy-poet** [comment]
the test passes when I run that- 
<img width="1104" alt="Screenshot 2022-05-03 at 14 32 57" src="https://user-images.githubusercontent.com/70343818/166462513-50bbbf42-63bf-4678-ba56-e3108fc09ba1.png">

**Comment by ikozakov** [comment]
> the test passes when I run that-

ok, then back to your error above, which test failed when you got this:
![image](https://user-images.githubusercontent.com/8004422/166462989-4cf461c8-2bd2-4971-8906-41cc2fea8a82.png)

**Comment by Lazy-poet** [comment]
@ikozakov  also, you could check out the logs of the last travis build run. seems most of those initial test failures went away after my last push.

https://app.travis-ci.com/github/wurmlab/sequenceserver/builds/250126150

**Comment by ikozakov** [comment]
> @ikozakov also, you could check out the logs of the last travis build run. seems most of those initial test failures went away after my last push.

i see now, awesome

**Comment by Lazy-poet** [comment]
> > the test passes when I run that-
> 
> ok, then back to your error above, which test failed when you got this: ![image](https://user-images.githubusercontent.com/8004422/166462989-4cf461c8-2bd2-4971-8906-41cc2fea8a82.png)

this happened on "disables sequence viewer links if hits are longer than 10kb", but it no longer happens

**Comment by ikozakov** [comment]
@Lazy-poet do you have an option to re-run those tests on travis? looks like tests are not stable and fail from time to time.
(we have 3 failures now, but locally on my mac I see absolutely different picture)

**Comment by Lazy-poet** [comment]
the build is disabled for me as well- but I can make an empty commit to force it to rerun

**Comment by yannickwurm** [comment]
(you both now *should* have the ability to click to rerun GitHub actions here by clicking)

**Comment by Lazy-poet** [comment]
@ikozakov after rerunning the build, it's left with only one failing check- "a browser can show hit sequence in a modal"

**Comment by Lazy-poet** [comment]
I think I might have found the cause. currently investigating, and I'll revert back

**Comment by Lazy-poet** [comment]
> I think I might have found the cause. currently investigating, and I'll revert in a few

<img width="979" alt="Screenshot 2022-05-03 at 16 24 42" src="https://user-images.githubusercontent.com/70343818/166484226-da9ff747-453f-4ac7-adad-fe0a715f379a.png">
