### ISSUE TITLE
Blast by similarity failed.

### ISSUE THREAD

**Issue by Akifb123** [wurmlab/sequenceserver#566]
When trying to use the blast tool  a prompt shows up saying:
BLAST failed abruptly (exit status: 3). Most likely there is a
problem with the BLAST+ binaries.

Kindly fix this error.

**Comment by yeban** [comment]
Hmm, I think this is the first time exit status 3 has been reported. I can try to fix the error, but I would need your help: 

Which version of SequenceServer and NCBI BLAST+ are you using? Did SequenceServer download BLAST+ or did you install it? What BLAST algorithm did you use?

**Comment by Akifb123** [comment]
I used the one present on the cotton fgd server. I don't exactly know the
version

**Comment by Akifb123** [comment]
I checked and the version is 2.0.0.rc8

**Comment by yeban** [comment]
Hi. I am sorry I lost track of this issue. I think you should to report this issue to the maintainers of cotton fgd server (if you haven't already). It is difficult for us to diagnose the issue if you are not running the SequenceServer instance yourself.
