### ISSUE TITLE
refactor exec call to avoid running shell on user provided parameters

### ISSUE THREAD

**Issue by robertvi** [wurmlab/sequenceserver#569]
If I understand correctly from a quick look at the code, user provided parameters are sanitised by forbidding all but a limited set of characters, which may already be enough to prevent shell code injection, but this is a little hard to verify. Why not also guard against any attempted code injection by invoking the exec call in sys.rb using the exec(command,args...) calling method, which doesn't invoke a shell on the user's parameters at all. I can see this would require some refactoring as the exec is currently using the shell to redirection stdout and stderr.

https://github.com/wurmlab/sequenceserver/blob/master/lib/sequenceserver/sys.rb 
https://apidock.com/ruby/Kernel/exec

Best wishes, and thanks for a great tool,
Rob

**Comment by yeban** [comment]
Thanks for the tip. It is informative.

`exec` can take similar/same options as the `spawn` method which includes the ability to redirect stdout and stderr. If the `exec(command, args...)` form can be combined with a hash of options, then maybe the refactoring required isn't much?

**Comment by yannickwurm** [comment]
@nathanweeks appropriately mentions that this change could also help resolve potential issues with unintended shell interpretation of special-characters present in filenames

**Comment by yannickwurm** [comment]
I think this is addressed thanks to work from @iQuxLE. I'll leave this issue open a bit longer for additional review - in case more is needed.
