### ISSUE TITLE
Multiple directories

### ISSUE THREAD

**Issue by marcadella** [wurmlab/sequenceserver#575]
Given that sequenceserver is not able to recursively get all the files found in directory set with `-d`, it would be super useful to be able to set `-d` multiple times.

**Comment by yannickwurm** [comment]
Thank you @marcadella - it used to be able to do recursion automatically, so it could be that we introduced a bug with a recent change.

**Comment by yeban** [comment]
SequenceServer scans databases directory recursively. If that is not the behaviour you see, can you please provide details of your setup, including the operating system, whether running inside docker or not, if there are symlinks in the databases directory, and if you think the filesystem might be in some way "special" (such as a networked file system, or file systems that are not as common as ext4 for linux).

If you have at least one BLAST database in the databases directory, SequenceServer will not automatically prompt you to create BLAST databases from other FASTA files. To do so, you must run `sequenceserver -m`.

If you are still interested in being able to specify multiple database directories, please add your support to #461 instead.

**Comment by marcadella** [comment]
I didn't mention that I create the databases myself so the directory doesn't contain any fasta files, only BLAST databases.
I tried on CENTOS 7 with Docker and one volume containing several databases each being located in it's own sub-directory. No symlinks and nothing special about the filesystem.
No db showed up in the UI, but now that I think about it, it might be related to #574
