### ISSUE TITLE
Run sequenceserver on a RHEL server

### ISSUE THREAD

**Issue by naity2** [wurmlab/sequenceserver#577]
Hi Team,

I am trying to run `sequenceserver` on a RHEL server and the installation seems to be successful as shown below. However, when running `sequenceserver` in a terminal, I got the `sequenceserver: command not found` error. I also tried running `which sequenceserver` and it looks like `sequenceserver` is not in any of those paths.

Please let me know if you have any suggestions. Thank you!

![image](https://user-images.githubusercontent.com/97263773/156470848-9f84da3d-dbb7-4224-89a6-9c99a862b455.png)

**Comment by yannickwurm** [comment]
Hi @naity2 - could you share your solution with the community? Thanks in advance, Yannick

**Comment by naity2** [comment]
Hi @yannickwurm, I ended up with running `/usr/local/bin/sequenceserver` instead although `/usr/local/bin` in already in `$PATH`. Thank you!
