### ISSUE TITLE
Where are BLAST results stored?

### ISSUE THREAD

**Issue by naity2** [wurmlab/sequenceserver#578]
Hi Team,

I was wondering where are BLAST results stored?

Thanks very much!

**Comment by yeban** [comment]
In `~/.sequenceserver`. Each job gets its own dir there and has a [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) for its name.

**Comment by naity2** [comment]
> In `~/.sequenceserver`. Each job gets its own dir there and has a [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) for its name.

Thank you!
