### ISSUE TITLE
Command Line Options does not work:  cannot load such file -- sequenceserver

### ISSUE THREAD

**Issue by lesser-panda** [wurmlab/sequenceserver#589]
Hi,

I have got Sequence Server up and running using Docker (tried both the docker hub image, as well as building with Dockerfile and the latest code). 

However, when I tried to use any commands showed here [https://sequenceserver.com/doc/](https://sequenceserver.com/doc/), like 
`sequenceserver -m` or
`sequenceserver --version` 

I got errors like this:

`
Traceback (most recent call last):
        5: from /sequenceserver/bin/sequenceserver:48:in <main>'
        4: from /usr/local/bundle/gems/slop-3.6.0/lib/slop.rb:65:in parse!'
        3: from /usr/local/bundle/gems/slop-3.6.0/lib/slop.rb:260:in parse!'
        2: from /sequenceserver/bin/sequenceserver:161:in block (2 levels) in <main>'
        1: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in require'
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in require': cannot load such file -- sequenceserver/version (LoadError)
`

The only command that works is `sequenceserver -h`

**Comment by yeban** [comment]
I cannot reproduce it with the latest image from docker hub, nor built from source locally. Please can you provide the full command?
