### ISSUE TITLE
System error in blast

### ISSUE THREAD

**Issue by uauy** [wurmlab/sequenceserver#624]
Hello. I was trying to blast a sequence in the jic wheat BLAST browser and came up with the following error: 

BLAST failed abruptly (exit status: 139). Most likely there is a problem with the BLAST+ binaries. 

The sequence I was using was below and I was blasting against Arina, Reedling and CS. Many thanks
Cristobal

>gw_A
TTGTTAATAAGATTCTCCTAATTT
GGGAACCACTGTAATTTCCCCTGTCCTAAAAAATGCATGTTTTTTTTTCTTAATTGTAGT
ACTACCCAAGCCTTAACCGATCAAAATGTTGCTCGAAAGGGATATGTACAGGTAATGTAT
CTGTCCTACTAGCTACTACCAGTGATTGTGTGTTACTTGTTAGGTGCAAATTTCCTTACA
TGTCTTGTTTGGTATTTTGCAGAGTGCTTTCTTCAAATGAAACCAACTCATACTGCTCGA
CCTACACAGTATCCTTCATACCATCTCTGTTCTTGTTTCAAATATCCTGTATTGGTAAGT
AATGTATGGGCCTTGTCAATTCTCACGGTAACACTTAACCAATAAAGATGCCCATTCTGC
AAAACCCCCAACTATGCTGTGGAGTATCGTGGTGTAAAGACAAAGGAGGAAAGGAGCATA
GAGCAATTTGTAAGTCTTATTCCCTAATGTGTTTGTTTTTGTGTTGATATTAGAAAGCCA
AATTCATTTACTTTATCTTGTATAAATTTTGTTACAGGAAGAACAGAAAGTCATTGAAGC
ACAGATGAGGGTGCGGCAGCAAGCACTTCAAGACGAAGAGGATAAGATGAAAAGAAAACA
GAGTAGGTGCTCTTCTAGCAGAACAATCGCTCCAACAACAGAAGTGGAGTATCGAGATAT
TTGCAGCACATCCTATTCAGGTCTGCACTAGATACGACAAATGTACACATTTAATAATGT
CAATTTTTCTGTAGTTTAATCTGATAACTTACAATTTACTATGTTCGTTGCAGTGCCATC
GTACCAATGTACCCAGCAAGAAACTGAATGTTGTTCGTCTGAGCCTTCATGTTCTGCTCA
GGCTAACATGCGGTCTTTCCATTCTAGGCATACTCGGTATGTTGTTTTATGTTTTATGTT
CCATCATACTTTACCGAAGCTCATATTGTTGGACAAATTCATT

**Comment by yannickwurm** [comment]
Hello Cristobal,
This is the generic issue tracker for the SequenceServer software. We don't run the JIC server. So I suspect you need to take this up directly with the managers of the JIC wheat blast server...

Kind regards,
Yannick
