### ISSUE TITLE
Error msg when trying to download the hits FASTA files

### ISSUE THREAD

**Issue by ypoh1** [wurmlab/sequenceserver#625]
Hi,

We used SequenceServer to host our databases of EukProt v3 (https://evocellbio.com/SAGdb/EukProt/), and we found there was errors when we tried to download the hits FASTA by clicking "FASTA" on top of the alignment, and it happened every time. The error message was as follows:

{"message":"SequenceServer::CommandFailed","title":"SequenceServer::CommandFailed","more_info":"/var/lib/gems/2.7.0/gems/sequenceserver-2.0.0/lib/sequenceserver/sys.rb:83:in `sys'\n/var/lib/gems/2.7.0/gems/forwardable-1.3.2/lib/forwardable.rb:238:in `sys'\n/var/lib/gems/2.7.0/gems/sequenceserver-2.0.0/lib/sequenceserver/sequence.rb:203:in `run'\n/var/lib/gems/2.7.0/gems/sequenceserver-2.0.0/lib/sequenceserver/sequence.rb:182:in `initialize'\n/var/lib/gems/2.7.0/gems/sequenceserver-2.0.0/lib/sequenceserver/routes.rb:139:in `new'\n/var/lib/gems/2.7.0/gems/sequenceserver-2.0.0/lib/sequenceserver/routes.rb:139:in `block in '\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1685:in `call'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1685:in `block in compile!'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1023:in `block (3 levels) in route!'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1042:in `route_eval'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1023:in `block (2 levels) in route!'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1071:in `block in process_route'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1069:in `catch'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1069:in `process_route'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1021:in `block in route!'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1018:in `each'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1018:in `route!'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1140:in `block in dispatch!'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `block in invoke'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `catch'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `invoke'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1135:in `dispatch!'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:949:in `block in call!'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `block in invoke'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `catch'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1112:in `invoke'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:949:in `call!'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:938:in `call'\n/var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/deflater.rb:44:in `call'\n/var/lib/gems/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:218:in `call'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1992:in `call'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1552:in `block in call'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1768:in `synchronize'\n/var/lib/gems/2.7.0/gems/sinatra-2.2.0/lib/sinatra/base.rb:1552:in `call'\n/var/lib/gems/2.7.0/gems/sequenceserver-2.0.0/lib/sequenceserver.rb:110:in `call'\n/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'\n/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'\n/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'\n/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'\n/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'"}

Also, the users had the same error message when they tried to download "FASTA of all hits" if they chose all taxa to blast, but sometimes we can download the FASTA file successfully. Do you have any idea how to fix this?

**Comment by yannickwurm** [comment]
Dear Yu-Ping @ypoh1 - is this still an issue? 

Are you able to provide an example of this failing? I imagine there could for example have been some strange characters in your FASTA identifiers?
