### ISSUE TITLE
BLAST failed abruptly (exit status: 3)

### ISSUE THREAD

**Issue by indirasb** [wurmlab/sequenceserver#628]
When trying to run BLAST I get a system error telling me to visit the website after a while. Error message is the following:

BLAST failed abruptly (exit status: 3). Most likely there is a problem with the BLAST+ binaries.

**Comment by yannickwurm** [comment]
Hi Indira, 
apologies - this must have been frustrating. 

However, this sounds like an issue specific to your installation. Perhaps you can ask whoever set up your SequenceServer instance. Alternatively if you are struggling with configuration issues, the community support forums at https://support.sequenceserver.com can be helpful. The hosted cloud servers may also be an alternative
