### ISSUE TITLE
There is no obvious way to document what sequences the databases contain

### ISSUE THREAD

**Issue by wwood** [wurmlab/sequenceserver#63]
In www-blast, you can hyperlink <code>Database</code> left of the drop down list of available databases.
http://openwetware.org/wiki/Image:Wwwblast.png

The idea is that on the page linked from there (which is just a straight HTML page in www-blast), a server admin can explain what each database contains, more verbosely than is possible within the drop-down box.

It would be good I think if seqserv had the same kind of ability. somehow. The only thing is, I personally have never seen one of those documentation pages filled out properly. Could just be me though. What do you guys think? Obviously this isn't a show-stopper bug.

**Comment by yeban** [comment]
Showing details like num-sequences have been discussed on another issue and is something I am happy to include. Ability to show additional details about the database is not in our mandate. These can be implemented outside SequenceServer with ease. For example, a user could author an HTML file describing the databases and link to it from the search form.
