### ISSUE TITLE
Integrating with JBrowse2

### ISSUE THREAD

**Issue by z626093820** [wurmlab/sequenceserver#641]
when i use the sequenceserver Integrating with JBrowse2, it show some problem。
The URL format for JBrowse2 searches is http://*******/?config=config.json&assembly=******&loc= **chrom**:start-end&tracks=****

In older versions of links.rb, there are only gene start and stop positions, not chromosome positions。 how should I modify the file to get the chromosome position。
for example：
"&loc=#{sequence_id}:#{first_hit_start-500}..#{first_hit_start+500}" \
how can i replace the sequence_id to chrom

THANK YOU !

**Comment by yannickwurm** [comment]
Hello z, SequenceServer only knows about the hit sequence... irrespective of whether it is a gene sequence or a genomic scaffold or entire chromosome. 
Thus if your jBrowse relies on chromosome positions, some extra logic is needed to convert from gene hit to chromosomal location. (Sometimes you have such information in a gene's description, sometimes in a gff...)
Closing for now as this is not something sequenceserver can change
