### ISSUE TITLE
how to use tree structure of database lists in docker command

### ISSUE THREAD

**Issue by wangc1106** [wurmlab/sequenceserver#674]
Dear professor Yannick Wurm

sequenceserver is so popular and excellent, i found the tree structure of database lists are using in this program.

but how to use tree structure of database lists in docker command?

any advice would would be highly appreciated

wang

**Comment by lukaszsobala** [comment]
You need to edit the file inside the container and restart it (probably bad practice) or bind mount your own config file like this: https://github.com/wurmlab/sequenceserver/issues/16#issuecomment-1936566239

This worked for me.
