### ISSUE TITLE
Update GH actions to use the latest version of BLAST

### ISSUE THREAD

**Issue by tadast** [wurmlab/sequenceserver#685]
[Dockerfile uses 2.14](https://github.com/wurmlab/sequenceserver/blob/master/Dockerfile#L3) while [GH actions use 2.12](https://github.com/wurmlab/sequenceserver/blob/a9a128b9d8db327c015c8a552b0c3b9c6831a283/.github/workflows/tests.yml#L37-L39), update so that both consistently use the latest version

**Comment by augeas** [comment]
Seeing some tests fail with BLAST+ 2.14: https://github.com/wurmlab/sequenceserver/actions/runs/6382926293/job/17322525393#step:11:1457

**Comment by augeas** [comment]
That's better: https://github.com/wurmlab/sequenceserver/actions/runs/6410537697/job/17404048052

**Comment by tadast** [comment]
Tests were failing on the main branch recently, looks like the same ones, if you pull the latest changes it should turn green hopefully

**Comment by augeas** [comment]
Yes, happier now, one rather trivial [PR](https://github.com/wurmlab/sequenceserver/pull/688).
