### ISSUE TITLE
installation problems on Ubuntu 23.10

### ISSUE THREAD

**Issue by thekswenson** [wurmlab/sequenceserver#706]
Hi folks...
  I'm trying to install sequenceserver on my Ubuntu machine.  I removed the (default) ruby 3.1 .deb package, replacing it with the 3.2.2 version offered in the snap package.
  
Doing `sudo gem install sequenceserver` fails with the following error:

```
ERROR:  Error installing sequenceserver:
	ERROR: Failed to build gem native extension.

    current directory: /root/.gem/gems/ox-2.14.17/ext/ox
/snap/bin/ruby extconf.rb
>>>>> Creating Makefile for ruby version 3.2.2 on x86_64-linux <<<<<
checking for rb_ext_ractor_safe() in ruby.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```

**Comment by yannickwurm** [comment]
That's frustrating. 
Is there an mkmf.log file in /root/.gem/gems/ox-2.14.17/ext/ox ?

**Comment by thekswenson** [comment]
AFAIK there is no snap development package for ruby.  I uninstalled the snap, and reinstalled 3.1 with the "ruby-dev" deb packages.  All is well now.  Thanks!
