### ISSUE TITLE
When exporting "Kablammo" plot as SVG or PNG, would be useful to have the query index & name appended

### ISSUE THREAD

**Issue by photocyte** [wurmlab/sequenceserver#736]
Current behavior, .svg is exported without a unique filename that can be linked to the query:
```
Kablammo-PKZILLA-1_CDS7-REVCOMP_scaffold_1158-RCC3426_pilon_152285-290527.svg
```

Desired behavior, .svg is exported **with** a unique filename that is directly linked to the query:
```
query-15_PKZILLA-1_CDS7_Kablammo-PKZILLA-1_CDS7-REVCOMP_scaffold_1158-RCC3426_pilon_152285-290527.svg
```

Relevant `Kablammo` SVG export button shown below:

<img width="856" alt="Screenshot 2024-04-08 at 8 02 10 AM" src="https://github.com/wurmlab/sequenceserver/assets/12517705/b7ad07c2-5aca-4f21-89a1-ec248c2bb89b">

**Comment by photocyte** [comment]
edit: I just noticed that the query name was already in the exported .svg! Mea culpa for missing that. **But**, would still be useful to include the query index i.e. ``query-15``

**Comment by Lazy-poet** [comment]
@yannickwurm this issue has been fixed in #777  and can now be closed

**Comment by yannickwurm** [comment]
super - thanks @Lazy-poet !

**Comment by yannickwurm** [comment]
@photocyte this isn't yet in [3.1.3](https://github.com/wurmlab/sequenceserver/commit/9c73fc11bba1763e4c75aa6fbb5ee6925bd66f3f), but it should be part of the next point release. Cheers!
