### ISSUE TITLE
blast/task.rb does not find blast binaries

### ISSUE THREAD

**Issue by kuntzagk** [wurmlab/sequenceserver#781]
In sequenceserver 3.1.2 the blast binaries are not found    Error is 
Errno::ENOENT - No such file or directory - blastn:

In the sequenceserver.conf the :bin: is pointing to the correct directory. 
Sequenceserver is working if I change task.rb to 

          help_text = `/usr/prg/ncbi-blast-2.16.0+/bin/#{algorithm} -help`

(Sorry, I do not do Ruby normally)

**Comment by tadast** [comment]
Hi @kuntzagk, sorry about this. 

I think it's coming from [here](https://github.com/wurmlab/sequenceserver/blob/269a429a25534fe1a4bf891b36251eb6ad024ece/lib/sequenceserver/blast/tasks.rb#L9). We'll need to fix this and release a new version.

In the meantime could you please run 

```
export PATH="$PATH:/usr/prg/ncbi-blast-2.16.0+/bin"
```

before running sequenceserver?

Alternatively you can add the same line to your shell profile (`~/.bash_profile`, `~/.profile`, `~/.zshrc` etc, depending on your OS and shell configuration).

**Comment by kuntzagk** [comment]
Hi,

We are running SequenceServer as an Phusion Passenger app and I'm not sure where to add the path in that case.

**Comment by tadast** [comment]
@kuntzagk we've released v3.1.3, if the issue remains in 3.1.3 please reopen this issue and provide a full stack trace of the error. Thanks for reporting!
