### ISSUE TITLE
Download local alignment

### ISSUE THREAD

**Issue by yannickwurm** [wurmlab/sequenceserver#92]
Three ideas emerging from a forum post [1]

When showing blast results
1. make it possible to download xxx bp up+downstream of the hitting region (currently we only allow the whole fasta sequence - which is problematic for whole chromosomes)
2. make it possible to download the blast-made local alignment (ie. the subject-query alignment, but in e.g. Clustal format)
3. make it possible to send the two aligning regions to a different service [2] to produce a high-quality local alignment

[1] http://seqanswers.com/forums/showthread.php?p=81505
[2] http://www.ebi.ac.uk/Tools/msa/muscle/

**Comment by vivekiitkgp** [comment]
I think first one would be a really nice feature to have in our subsequent release. What say @yeban ?

**Comment by yeban** [comment]
Not sure. More eager to remove '-pre' from 1.0 first :).

**Comment by vivekiitkgp** [comment]
Time to bring in milestones too ;)

**Comment by yannickwurm** [comment]
@vivekiitkgp - first priority is to get a stable release out

**Comment by yeban** [comment]
@yannickwurm We have the ability to export alignment in master. There must be a tool that users can use to convert it to Clustal and myriad other formats. Or we could provide a script later, through /doc page of the site. Further, the ability to _send_ alignments from our reports page to another service or services is a non-trivial design problem. It's not like all services have the same API. Which one do we program for? What kind of plugin-API should we provide to facilitate such integration? These are worth considering if we were providing a hosted service. At the moment, users can always simply upload files downloaded from SequenceServer to another service. Finally, if a genome community is interested in integrating SequenceServer with other tools in creative ways, I am open to including few changes in the source code to facilitate it (like in case of lepbase).

I would thus like to close this issue and open a new one only for point 1.

**Comment by yannickwurm** [comment]
Download of local alignment is in fasta format? 

ok for close/reopen

**Comment by yeban** [comment]
In custom, plain-text format. 5 lines per alignment: query and hit id and match coordinates, and alignment query, middle and subject line as output by BLAST. For example, alignment download of two selected hits is shown below.

```
SI2.2.0_06267 1 597
SI2.2.0_06267 1 199
MNTLWLSLWDYPGKLPLNFMVFDTKDDLQAAYWRDPYSIPLAVIFEDPQPISQRLIYEIRTNPSYTLPPPPTKLYSAPISCRKNKTGHWMDDILSIKTGESCPVNNYLHSGFLALQMITDITKIKLENSDVTIPDIKLIMFPKEPYTADWMLAFRVVIPLYMVLALSQFITYLLILIVGEKENKIKEGMKMMGLNDSVF
MNTLWLSLWDYPGKLPLNFMVFDTKDDLQAAYWRDPYSIPLAVIFEDPQPISQRLIYEIRTNPSYTLPPPPTKLYSAPISCRKNKTGHWMDDILSIKTGESCPVNNYLHSGFLALQMITDITKIKLENSDVTIPDIKLIMFPKEPYTADWMLAFRVVIPLYMVLALSQFITYLLILIVGEKENKIKEGMKMMGLNDSVF
MNTLWLSLWDYPGKLPLNFMVFDTKDDLQAAYWRDPYSIPLAVIFEDPQPISQRLIYEIRTNPSYTLPPPPTKLYSAPISCRKNKTGHWMDDILSIKTGESCPVNNYLHSGFLALQMITDITKIKLENSDVTIPDIKLIMFPKEPYTADWMLAFRVVIPLYMVLALSQFITYLLILIVGEKENKIKEGMKMMGLNDSVF
SI2.2.0_06267 79 150
SI2.2.0_11870 62 85
DLQAAYWRDPYSIPLAVIFEDPQP
+++ +Y+RD   +PL + F+D +P
NIKKSYFRDRLVLPLFIYFDDVEP
```

I have sometimes wondered if we can export as SAM, but I don't see a clear solution there (e.g., how will translated nucleotide searches be encoded, generating CIGAR string).

**Comment by yeban** [comment]
Closing as per above discussion. See #324.

**Comment by yannickwurm** [comment]
Hey @yeban, lets not invent "yet another alignment format". 
I suggest a slight reformatting of what you currently propose to make it multi-fasta-like and to clearly separate the different alignmetns. Eg: 

```FASTA
>SI2.2.0_06267:1-597
MNTLWLSLWDYPGKLPLNFMVFDTKDDLQAAYWRDPYSIPLAVIFEDPQPISQRLIYEIRTNPSYTLPPPPTKLYSAPISCRKNKTGHWMDDILSIKTGESCPVNNYLHSGFLALQMITDITKIKLENSDVTIPDIKLIMFPKEPYTADWMLAFRVVIPLYMVLALSQFITYLLILIVGEKENKIKEGMKMMGLNDSVF
>SI2.2.0_06267:1-199
MNTLWLSLWDYPGKLPLNFMVFDTKDDLQAAYWRDPYSIPLAVIFEDPQPISQRLIYEIRTNPSYTLPPPPTKLYSAPISCRKNKTGHWMDDILSIKTGESCPVNNYLHSGFLALQMITDITKIKLENSDVTIPDIKLIMFPKEPYTADWMLAFRVVIPLYMVLALSQFITYLLILIVGEKENKIKEGMKMMGLNDSVF
>SI2.2.0_06267:1-597_alignment_SI2.2.0_06267:1-199
MNTLWLSLWDYPGKLPLNFMVFDTKDDLQAAYWRDPYSIPLAVIFEDPQPISQRLIYEIRTNPSYTLPPPPTKLYSAPISCRKNKTGHWMDDILSIKTGESCPVNNYLHSGFLALQMITDITKIKLENSDVTIPDIKLIMFPKEPYTADWMLAFRVVIPLYMVLALSQFITYLLILIVGEKENKIKEGMKMMGLNDSVF
>SI2.2.0_06267:79-150
DLQAAYWRDPYSIPLAVIFEDPQP
>SI2.2.0_11870 62 85
NIKKSYFRDRLVLPLFIYFDDVEP
>SI2.2.0_06267:79-150_alignment_SI2.2.0_11870:62-85
+++ +Y+RD   +PL + F+D +P
```
